In [ ]:
# Machine Learning-Based Prediction of Degradation in PEM Fuel Cells Using Time-Series Operational Data

## Notebook 01: Project Setup and Data Loading

### Objective
The objective of this notebook is to set up the project environment, import the required libraries, define the project directory structure, and load the GreenLight Innovation PEM fuel cell datasets for further analysis.

---

In [ ]:
## Workflow

This notebook covers the following tasks:

1. Import required libraries
2. Configure display settings
3. Define project paths
4. Locate and load the dataset files
5. Verify successful data loading
   - Verify dataset import
   - Verify dataset dimensions
   - Verify variable names
   - Verify data types
   - Verify missing values
   - Verify duplicate records
   - Verify memory usage
   - Verify dataset consistency
   - Verify polarization curve datasets
6. Produce an initial dataset summary
7. Record initial observations

In [2]:
# ============================================================
# Import Required Libraries
# ============================================================

import os #Standard library to interact with the operating system (files, folders, environment)
from pathlib import Path #Modern way to work with file and folder paths

import pandas as pd
import numpy as np

In [ ]:
## Configure Display Settings

To make the dataset easier to inspect, we configure pandas to display more rows, columns, and wider tables without truncation.

In [3]:
# ============================================================
# Configure Pandas Display Settings
# ============================================================

# Display all columns
pd.set_option('display.max_columns', None)

# Display up to 100 rows when needed
pd.set_option('display.max_rows', 100)

# Prevent line wrapping of wide tables
pd.set_option('display.width', 1000)

# Display full content of each column
pd.set_option('display.max_colwidth', None)

print("Pandas display settings configured successfully.")

Pandas display settings configured successfully.

In [ ]:
## Define Project Paths

This section defines reusable folder paths for the project. Using paths instead of hard-coded file locations makes the notebook easier to maintain and reproduce.

In [4]:
# ============================================================
# Define Project Paths
# ============================================================

# Current notebook location may be inside the notebooks folder.
# Therefore, we define the project root as the parent folder of the notebooks folder.
PROJECT_ROOT = Path.cwd().parent

# Define important project folders
DATA_DIR = PROJECT_ROOT / "data"
RAW_DATA_DIR = DATA_DIR / "raw"
PROCESSED_DATA_DIR = DATA_DIR / "processed"
FIGURES_DIR = PROJECT_ROOT / "figures"
RESULTS_DIR = PROJECT_ROOT / "results"

# Display paths
print("Project root:", PROJECT_ROOT)
print("Raw data folder:", RAW_DATA_DIR)
print("Processed data folder:", PROCESSED_DATA_DIR)
print("Figures folder:", FIGURES_DIR)
print("Results folder:", RESULTS_DIR)

Project root: C:\Users\usman\Desktop\PEMFC_Dissertation
Raw data folder: C:\Users\usman\Desktop\PEMFC_Dissertation\data\raw
Processed data folder: C:\Users\usman\Desktop\PEMFC_Dissertation\data\processed
Figures folder: C:\Users\usman\Desktop\PEMFC_Dissertation\figures
Results folder: C:\Users\usman\Desktop\PEMFC_Dissertation\results

In [ ]:
## Locate Raw Dataset Files

This section identifies all CSV files stored in the raw data folder.

In [5]:
# ============================================================
# Locate Raw Dataset Files
# ============================================================

# Find all CSV files in the raw data folder
csv_files = sorted(RAW_DATA_DIR.glob("*.csv"))

# Display number of files found
print(f"Number of CSV files found: {len(csv_files)}")

# Display file names
for file in csv_files:
    print(file.name)

Number of CSV files found: 22
1000_h.csv
100_h.csv
150_h.csv
200_h.csv
250_h.csv
300_h.csv
350_h.csv
400_h.csv
450_h.csv
500_h.csv
50_h.csv
550_h.csv
600_h.csv
650_h.csv
700_h.csv
750_h.csv
800_h.csv
850_h.csv
900_h.csv
950_h.csv
Polarization_curves.csv
Polarization_curves_after_12h_rest.csv

In [ ]:
## Load the Dataset Files

This section loads all CSV files into Python as pandas DataFrames and stores them in a dictionary. Each dataset is accessed using its filename as the key.

In [6]:
# ============================================================
# Load All CSV Files
# ============================================================

# Dictionary to store all datasets
datasets = {}

# Read each CSV file
for file in csv_files:
    datasets[file.stem] = pd.read_csv(file)

print(f"Successfully loaded {len(datasets)} datasets.")

C:\Users\usman\AppData\Local\Temp\ipykernel_21036\3184011635.py:10: DtypeWarning: Columns (0: time, 1: current, 2: voltage, 3: power, 4: pressure_anode_inlet, 5: pressure_anode_outlet, 6: pressure_cathode_inlet, 7: pressure_cathode_outlet, 8: temp_anode_endplate, 9: temp_anode_dewpoint_water, 10: temp_anode_inlet, 11: temp_anode_outlet, 12: temp_cathode_dewpoint_water, 13: temp_cathode_inlet, 14: temp_cathode_outlet, 15: total_anode_stack_flow, 16: total_cathode_stack_flow) have mixed types. Specify dtype option on import or set low_memory=False.
  datasets[file.stem] = pd.read_csv(file)

Successfully loaded 22 datasets.

In [ ]:
## Verify Successful Data Loading

After loading the files, the datasets are checked to confirm that each file was imported correctly. This includes checking the number of rows, columns, missing values, data types, and memory usage.

In [9]:
# ============================================================
# Verify Successful Data Loading
# ============================================================

summary_data = []

for name, df in datasets.items():
    summary_data.append({
        "dataset_name": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "missing_values": df.isna().sum().sum(),
        "duplicate_rows": df.duplicated().sum(),
        "memory_usage_MB": round(df.memory_usage(deep=True).sum() / (1024 ** 2), 2)
    })

dataset_summary = pd.DataFrame(summary_data)

dataset_summary

                          dataset_name    rows  columns  missing_values  duplicate_rows  memory_usage_MB
0                               1000_h  221842       18               0               0           130.09
1                                100_h  179362       18               0               0           107.72
2                                150_h  179362       18               0               0           107.72
3                                200_h  179362       18               0               0           107.68
4                                250_h  179362       18               0               0           107.69
5                                300_h  179362       18               0               0           107.71
6                                350_h  179362       18               0               0           107.72
7                                400_h  179362       18               0               0           107.69
8                                450_h  179362       18               0               0           107.73
9                                500_h  179362       18               0               0           107.72
10                                50_h  179362       18               0               0           107.71
11                               550_h  179362       18               0               0           107.69
12                               600_h  179362       18               0               0           107.73
13                               650_h  179362       18               0               0           107.73
14                               700_h  179362       18               0               0           107.73
15                               750_h  179362       18               0               0           107.73
16                               800_h  179362       18               0               0           107.73
17                               850_h  179362       18               0               0           107.73
18                               900_h  179362       18               0               0           107.73
19                               950_h  179362       18               0               0           107.73
20                 Polarization_curves      48       54             924               3             0.10
21  Polarization_curves_after_12h_rest      48       49             741               3             0.09

In [ ]:
## Display Column Names for Each Dataset

This section displays the variable names in each dataset to check whether the files have consistent structure.

In [11]:
# ============================================================
# Display Column Names for Each Dataset
# ============================================================

for name, df in datasets.items():
    print(f"\nDataset: {name}")
    print("-" * 80)
    print(list(df.columns))

Dataset: 1000_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 100_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 150_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 200_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 250_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 300_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 350_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 400_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 450_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 500_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 50_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 550_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 600_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 650_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 700_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 750_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 800_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 850_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 900_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: 950_h
--------------------------------------------------------------------------------
['Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

Dataset: Polarization_curves
--------------------------------------------------------------------------------
['admin [Administrator]', 'G17-2392', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53']

Dataset: Polarization_curves_after_12h_rest
--------------------------------------------------------------------------------
['admin [Administrator]', 'G17-2392', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4', 'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13', 'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17', 'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48']

In [ ]:
The operational datasets include an additional column named `Unnamed: 0`, which appears to represent an exported index column rather than an experimental variable. This column will be removed during the preprocessing stage, while the original raw files will remain unchanged.

In [ ]:
## Check Data Types

This section checks the data types assigned to each variable after importing the CSV files.

In [12]:
# ============================================================
# Check Data Types for Each Dataset
# ============================================================

for name, df in datasets.items():
   print(f"\nDataset: {name}")
   print("-" * 80)
   print(df.dtypes)

Dataset: 1000_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 100_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 150_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 200_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 250_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 300_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 350_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 400_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 450_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 500_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 50_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 550_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 600_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 650_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 700_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 750_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 800_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 850_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 900_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: 950_h
--------------------------------------------------------------------------------
Unnamed: 0                      int64
time                           object
current                        object
voltage                        object
power                          object
pressure_anode_inlet           object
pressure_anode_outlet          object
pressure_cathode_inlet         object
pressure_cathode_outlet        object
temp_anode_endplate            object
temp_anode_dewpoint_water      object
temp_anode_inlet               object
temp_anode_outlet              object
temp_cathode_dewpoint_water    object
temp_cathode_inlet             object
temp_cathode_outlet            object
total_anode_stack_flow         object
total_cathode_stack_flow       object
dtype: object

Dataset: Polarization_curves
--------------------------------------------------------------------------------
admin [Administrator]        str
G17-2392                     str
Unnamed: 2                   str
Unnamed: 3                   str
Unnamed: 4               float64
Unnamed: 5                   str
Unnamed: 6                   str
Unnamed: 7                   str
Unnamed: 8                   str
Unnamed: 9               float64
Unnamed: 10                  str
Unnamed: 11                  str
Unnamed: 12                  str
Unnamed: 13                  str
Unnamed: 14              float64
Unnamed: 15                  str
Unnamed: 16                  str
Unnamed: 17                  str
Unnamed: 18                  str
Unnamed: 19              float64
Unnamed: 20                  str
Unnamed: 21                  str
Unnamed: 22                  str
Unnamed: 23                  str
Unnamed: 24              float64
Unnamed: 25                  str
Unnamed: 26                  str
Unnamed: 27                  str
Unnamed: 28                  str
Unnamed: 29              float64
Unnamed: 30                  str
Unnamed: 31                  str
Unnamed: 32                  str
Unnamed: 33                  str
Unnamed: 34              float64
Unnamed: 35                  str
Unnamed: 36                  str
Unnamed: 37                  str
Unnamed: 38                  str
Unnamed: 39              float64
Unnamed: 40                  str
Unnamed: 41                  str
Unnamed: 42                  str
Unnamed: 43                  str
Unnamed: 44              float64
Unnamed: 45                  str
Unnamed: 46                  str
Unnamed: 47                  str
Unnamed: 48                  str
Unnamed: 49              float64
Unnamed: 50                  str
Unnamed: 51                  str
Unnamed: 52                  str
Unnamed: 53                  str
dtype: object

Dataset: Polarization_curves_after_12h_rest
--------------------------------------------------------------------------------
admin [Administrator]        str
G17-2392                     str
Unnamed: 2                   str
Unnamed: 3                   str
Unnamed: 4               float64
Unnamed: 5                   str
Unnamed: 6                   str
Unnamed: 7                   str
Unnamed: 8                   str
Unnamed: 9               float64
Unnamed: 10                  str
Unnamed: 11                  str
Unnamed: 12                  str
Unnamed: 13                  str
Unnamed: 14              float64
Unnamed: 15                  str
Unnamed: 16                  str
Unnamed: 17                  str
Unnamed: 18                  str
Unnamed: 19              float64
Unnamed: 20                  str
Unnamed: 21                  str
Unnamed: 22                  str
Unnamed: 23                  str
Unnamed: 24              float64
Unnamed: 25                  str
Unnamed: 26                  str
Unnamed: 27                  str
Unnamed: 28                  str
Unnamed: 29              float64
Unnamed: 30                  str
Unnamed: 31                  str
Unnamed: 32                  str
Unnamed: 33                  str
Unnamed: 34              float64
Unnamed: 35                  str
Unnamed: 36                  str
Unnamed: 37                  str
Unnamed: 38                  str
Unnamed: 39              float64
Unnamed: 40                  str
Unnamed: 41                  str
Unnamed: 42                  str
Unnamed: 43                  str
Unnamed: 44              float64
Unnamed: 45                  str
Unnamed: 46                  str
Unnamed: 47                  str
Unnamed: 48                  str
dtype: object

In [ ]:
## Initial Observations from Data Loading

The data loading process confirmed that 22 CSV files were successfully imported into Python. Twenty files correspond to operational PEM fuel cell test data, while two files contain polarization curve data.

The operational datasets have a consistent structure, with 18 columns in each file. Most operational files contain 179,362 observations, while the 1000-hour dataset contains 221,842 observations. No missing values or duplicate rows were detected in the operational datasets at this stage.

The polarization curve files differ significantly from the operational datasets. They contain fewer rows, more columns, missing values, and duplicate rows. Therefore, these files should be treated separately from the main time-series operational datasets.

An important observation is that most operational variables were imported as object data types rather than numerical types. This suggests that data type conversion will be required in a later preprocessing step before statistical analysis and machine learning modelling.

The operational datasets include an additional column named `Unnamed: 0`, which appears to represent an exported index column rather than an experimental variable. This column will be removed during the preprocessing stage, while the original raw files will remain unchanged.

In [ ]:
## C3.6.8 Dataset Consistency Verification

This section checks whether the operational datasets have a consistent structure. The verification includes checking column names, column order, number of columns, and data types across all operational files.

In [13]:
# ============================================================
# C3.6.8 Dataset Consistency Verification
# ============================================================

# Separate operational datasets from polarization curve datasets
operational_datasets = {
    name: df for name, df in datasets.items()
    if "Polarization" not in name
}

polarization_datasets = {
    name: df for name, df in datasets.items()
    if "Polarization" in name
}

print(f"Operational datasets: {len(operational_datasets)}")
print(f"Polarization datasets: {len(polarization_datasets)}")

Operational datasets: 20
Polarization datasets: 2

In [14]:
# Use the first operational dataset as the reference structure
reference_name = list(operational_datasets.keys())[0]
reference_df = operational_datasets[reference_name]

reference_columns = list(reference_df.columns)
reference_dtypes = reference_df.dtypes.astype(str).to_dict()

consistency_results = []

for name, df in operational_datasets.items():
    consistency_results.append({
        "dataset_name": name,
        "same_number_of_columns": df.shape[1] == len(reference_columns),
        "same_column_names": set(df.columns) == set(reference_columns),
        "same_column_order": list(df.columns) == reference_columns,
        "same_data_types": df.dtypes.astype(str).to_dict() == reference_dtypes
    })

consistency_summary = pd.DataFrame(consistency_results)

consistency_summary

   dataset_name  same_number_of_columns  same_column_names  same_column_order  same_data_types
0        1000_h                    True               True               True             True
1         100_h                    True               True               True             True
2         150_h                    True               True               True             True
3         200_h                    True               True               True             True
4         250_h                    True               True               True             True
5         300_h                    True               True               True             True
6         350_h                    True               True               True             True
7         400_h                    True               True               True             True
8         450_h                    True               True               True             True
9         500_h                    True               True               True             True
10         50_h                    True               True               True             True
11        550_h                    True               True               True             True
12        600_h                    True               True               True             True
13        650_h                    True               True               True             True
14        700_h                    True               True               True             True
15        750_h                    True               True               True             True
16        800_h                    True               True               True             True
17        850_h                    True               True               True             True
18        900_h                    True               True               True             True
19        950_h                    True               True               True             True

In [ ]:
## C3.7 Initial Dataset Summary

The following summary provides an overview of the imported datasets, including the number of datasets, observations, variables, data consistency, and overall readiness for further preprocessing.

In [15]:
# ============================================================
# C3.7 Initial Dataset Summary
# ============================================================

summary = {
    "Total datasets": len(datasets),
    "Operational datasets": len(operational_datasets),
    "Polarization datasets": len(polarization_datasets),
    "Operational datasets structurally consistent": consistency_summary[
        ["same_number_of_columns",
         "same_column_names",
         "same_column_order",
         "same_data_types"]
    ].all().all(),
    "Operational datasets contain missing values":
        dataset_summary.loc[
            dataset_summary["dataset_name"].isin(operational_datasets.keys()),
            "missing_values"
        ].sum() > 0,
    "Operational datasets contain duplicate rows":
        dataset_summary.loc[
            dataset_summary["dataset_name"].isin(operational_datasets.keys()),
            "duplicate_rows"
        ].sum() > 0
}

summary_df = pd.DataFrame(
    summary.items(),
    columns=["Item", "Result"]
)

summary_df

                                           Item Result
0                                Total datasets     22
1                          Operational datasets     20
2                         Polarization datasets      2
3  Operational datasets structurally consistent   True
4   Operational datasets contain missing values  False
5   Operational datasets contain duplicate rows  False

In [ ]:
# Summary

## Objectives Achieved

- Successfully configured the project environment for data loading.
- Imported the required Python libraries.
- Configured pandas display settings.
- Defined reusable project paths.
- Located all raw dataset files.
- Loaded all datasets into Python.
- Verified successful data loading.
- Validated dataset dimensions, variable names, data types, missing values, duplicate records, memory usage, and dataset consistency.
- Produced an initial dataset summary.
- Recorded key observations.

## Key Findings

- Twenty-two CSV datasets were successfully imported.
- Twenty operational datasets share an identical structure.
- The polarization curve datasets have a different structure and will require separate preprocessing.
- The `Unnamed: 0` column appears to be an exported index column.
- Most operational variables were imported as `object` data types and will require conversion during preprocessing.
- The original datasets remain unchanged and are ready for the next stage of analysis.

## Next Step

Proceed to **C4 – Initial Data Understanding**.

In [ ]:
## Polarization Dataset Verification

The polarization curve datasets are verified separately from the operational datasets because they represent a different experimental data structure. This section examines their dimensions, variables, data types, missing values, duplicate records, memory usage, and structural consistency.

In [16]:
# ============================================================
# C3.9.2 Polarization Dataset Verification
# ============================================================

polarization_summary = []

for name, df in polarization_datasets.items():

    polarization_summary.append({
        "dataset_name": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "missing_values": df.isna().sum().sum(),
        "duplicate_rows": df.duplicated().sum(),
        "memory_usage_MB": round(
            df.memory_usage(deep=True).sum() / (1024 ** 2), 2
        )
    })

polarization_summary = pd.DataFrame(polarization_summary)

polarization_summary

                         dataset_name  rows  columns  missing_values  duplicate_rows  memory_usage_MB
0                 Polarization_curves    48       54             924               3             0.10
1  Polarization_curves_after_12h_rest    48       49             741               3             0.09

In [17]:
# ============================================================
# Compare Polarization Dataset Structures
# ============================================================

reference_polarization = list(polarization_datasets.values())[0]

comparison_results = []

for name, df in polarization_datasets.items():

    comparison_results.append({

        "dataset_name": name,

        "same_number_of_columns":
            df.shape[1] == reference_polarization.shape[1],

        "same_column_names":
            list(df.columns) == list(reference_polarization.columns),

        "same_data_types":
            df.dtypes.astype(str).tolist()
            ==
            reference_polarization.dtypes.astype(str).tolist()

    })

polarization_consistency = pd.DataFrame(comparison_results)

polarization_consistency

                         dataset_name  same_number_of_columns  same_column_names  same_data_types
0                 Polarization_curves                    True               True             True
1  Polarization_curves_after_12h_rest                   False              False            False

In [ ]:
## C3.9.3 Initial Polarization Dataset Observations

The verification process identified two polarization curve datasets within the GreenLight Innovation dataset.

Both datasets contain 48 observations; however, they differ in their overall structure. The `Polarization_curves` dataset contains 54 variables, whereas the `Polarization_curves_after_12h_rest` dataset contains 49 variables. This structural difference indicates that the datasets represent different experimental outputs and should not be treated as identical.

Both datasets contain missing values and three duplicate records. These observations suggest that additional preprocessing and validation will be required before the polarization datasets can be analysed.

A structural comparison further confirmed that the two polarization datasets differ in the number of variables, variable names, and data types. These differences are expected and do not indicate errors during the data loading process.

Unlike the operational time-series datasets, the polarization curve datasets represent fuel cell performance characterisation under specific operating conditions rather than continuous operational measurements. Consequently, they will be processed and analysed separately throughout the remainder of this research.

The original polarization datasets remain unchanged and are preserved within the `data/raw/` directory.