In [ ]:
# C5. Data Cleaning

## Objective

The objective of this notebook is to transform the merged operational dataset into a clean, consistent, and analysis-ready dataset while preserving the integrity of the original experimental observations.

This notebook focuses on identifying and correcting structural issues within the merged dataset, including unnecessary variables, metadata rows, and incorrect data types. No modifications are made to the original experimental measurements.

The cleaned dataset produced in this notebook will serve as the primary dataset for all subsequent stages of the dissertation, including data quality assessment, exploratory data analysis, feature engineering, and machine learning model development.

In [ ]:
## Workflow

This notebook covers the following tasks:

1. Import required libraries
2. Configure display settings
3. Define project paths
4. Load the merged operational dataset
5. Perform an initial cleaning assessment
6. Perform structural cleaning
   - Remove unnecessary columns
   - Remove metadata rows
7. Convert operational variables to appropriate data types
8. Verify successful cleaning
   - Dataset dimensions
   - Data types
   - Missing values
   - Operating-hour integrity
   - Numerical variable verification
9. Save the cleaned operational dataset
10. Generate the cleaning summary
11. Record key findings and initial observations

In [1]:
# ============================================================
# Import Required Libraries
# ============================================================

from pathlib import Path

import pandas as pd
import numpy as np

In [2]:
# ============================================================
# Configure Display Settings
# ============================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)
pd.set_option("display.max_colwidth", None)

In [3]:
# ============================================================
# Define Project Paths
# ============================================================

PROJECT_ROOT = Path.cwd().parent

PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

print("Project Root:", PROJECT_ROOT)
print("Processed Data Folder:", PROCESSED_DATA_DIR)

Project Root: C:\Users\usman\Desktop\PEMFC_Dissertation
Processed Data Folder: C:\Users\usman\Desktop\PEMFC_Dissertation\data\processed

In [ ]:
## C5.1 Load the Merged Operational Dataset

The merged operational dataset created during Notebook 02 is loaded for cleaning.

This dataset represents the original experimental observations and has not yet undergone any preprocessing or structural modifications.

In [4]:
# ============================================================
# Load Merged Operational Dataset
# ============================================================

merged_dataset = pd.read_csv(
    PROCESSED_DATA_DIR / "operational_merged_raw.csv",
    low_memory=False
)

print("Merged operational dataset loaded successfully.")

Merged operational dataset loaded successfully.

In [ ]:
## C5.2 Initial Cleaning Assessment

Before performing any cleaning operations, it is important to identify and document the structural issues present within the merged dataset.

This assessment establishes the baseline condition of the dataset and provides justification for each cleaning step performed later in this notebook.

The assessment focuses on identifying:

- unnecessary variables;
- metadata rows;
- incorrect data types;
- variable naming issues.

In [5]:
# ============================================================
# Initial Cleaning Assessment
# ============================================================

print("=" * 60)
print("Dataset Shape")
print("=" * 60)
print(merged_dataset.shape)

print("\n")

print("=" * 60)
print("Column Names")
print("=" * 60)
print(list(merged_dataset.columns))

print("\n")

print("=" * 60)
print("Current Data Types")
print("=" * 60)
print(merged_dataset.dtypes)

============================================================
Dataset Shape
============================================================
(3629720, 19)


============================================================
Column Names
============================================================
['operating_hour', 'Unnamed: 0', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']


============================================================
Current Data Types
============================================================
operating_hour                 int64
Unnamed: 0                     int64
time                             str
current                          str
voltage                          str
power                            str
pressure_anode_inlet             str
pressure_anode_outlet            str
pressure_cathode_inlet           str
pressure_cathode_outlet          str
temp_anode_endplate              str
temp_anode_dewpoint_water        str
temp_anode_inlet                 str
temp_anode_outlet                str
temp_cathode_dewpoint_water      str
temp_cathode_inlet               str
temp_cathode_outlet              str
total_anode_stack_flow           str
total_cathode_stack_flow         str
dtype: object

In [ ]:
## Dataset Snapshot Before Cleaning

Before applying any cleaning procedures, a representative snapshot of the merged operational dataset is displayed.

This snapshot provides a visual record of the dataset's original structure and confirms the presence of metadata rows and the exported index column prior to any modifications.

In [6]:
# ============================================================
# Dataset Snapshot Before Cleaning
# ============================================================

merged_dataset.head(5)

,operating_hour,Unnamed: 0,time,current,voltage,power,pressure_anode_inlet,pressure_anode_outlet,pressure_cathode_inlet,pressure_cathode_outlet,temp_anode_endplate,temp_anode_dewpoint_water,temp_anode_inlet,temp_anode_outlet,temp_cathode_dewpoint_water,temp_cathode_inlet,temp_cathode_outlet,total_anode_stack_flow,total_cathode_stack_flow
0,50,0,s,A,V,W,kPag,kPag,kPag,kPag,°C,°C,°C,°C,°C,°C,°C,NLPM,NLPM
1,50,1,Elapsed time,current,voltage,power,pressure_anode_inlet,pressure_anode_outlet,pressure_cathode_inlet,pressure_cathode_outlet,temp_anode_endplate,temp_anode_dewpoint_water,temp_anode_inlet,temp_anode_outlet,temp_cathode_dewpoint_water,temp_cathode_inlet,temp_cathode_outlet,total_anode_stack_flow,total_cathode_stack_flow
2,50,2,1.761,0,0.9375,0,109.901303,110.32725,109.800128,108.792114,83.128159,54.464745,71.951462,39.453175,64.464287,69.673592,56.337543,0.07,0.291
3,50,3,2.761,0,0.9375,0,110.103653,110.32725,109.800128,108.893387,83.078773,54.464745,71.902084,39.387039,64.439034,69.661247,56.324917,0.07,0.291
4,50,4,3.761,0,0.9372,0,110.306003,110.32725,109.800128,108.792114,83.078773,54.529343,71.88974,39.41349,64.486618,69.685936,56.299664,0.07,0.291

In [ ]:
## C5.1 Structural Cleaning

The merged operational dataset currently contains structural elements that are not part of the experimental observations.

The objective of this section is to remove unnecessary information while preserving every genuine experimental measurement.

Structural cleaning includes:

- removing unnecessary variables;
- removing metadata rows;
- standardising the dataset structure.

These operations improve the quality of the dataset without modifying the underlying experimental data.

In [ ]:
### Remove Unnecessary Variables

The merged operational dataset contains the variable `Unnamed: 0`, which represents the exported row index from the original CSV files.

This variable does not describe any physical property of the PEM fuel cell and has no analytical value.

It is therefore removed before further preprocessing.

In [14]:
# ============================================================
# Remove Unnecessary Variables
# ============================================================

cleaned_dataset = merged_dataset.drop(columns=["Unnamed: 0"])

print("'Unnamed: 0' removed successfully.")

'Unnamed: 0' removed successfully.

In [15]:
# ============================================================
# Verify Column Removal
# ============================================================

print("Number of variables after column removal:",
      cleaned_dataset.shape[1])

print("\nCurrent variables:\n")

print(list(cleaned_dataset.columns))

Number of variables after column removal: 18

Current variables:

['operating_hour', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

In [ ]:
### Verify Structural Integrity After Column Removal

Before continuing, the dataset structure is verified to ensure that only the unnecessary index column has been removed and that all experimental variables remain intact.

In [9]:
# ============================================================
# Verify Structural Integrity After Column Removal
# ============================================================

print("Rows :", cleaned_dataset.shape[0])
print("Columns :", cleaned_dataset.shape[1])

print("\nMissing 'Unnamed: 0':",
      "Unnamed: 0" not in cleaned_dataset.columns)

Rows : 3629720
Columns : 18

Missing 'Unnamed: 0': True

In [ ]:
### Inspect Metadata Rows Before Removal

Before removing the metadata rows, it is important to confirm that they are present at the beginning of each operating-hour experiment.

The first operating-hour experiment (`50_h`) is inspected as a representative example. This allows us to visually distinguish the metadata rows from the genuine experimental observations and provides justification for their removal.

The inspection should demonstrate that:

- the first row contains measurement units;
- the second row contains variable descriptions;
- the third row represents the first genuine experimental observation.

Once this structure has been confirmed, the same cleaning procedure will be applied consistently to every operating-hour experiment.

In [10]:
# ============================================================
# Inspect Metadata Rows Before Removal
# ============================================================

# Display first five rows of the 50-hour experiment

cleaned_dataset.loc[
    cleaned_dataset["operating_hour"] == 50
].head()

,operating_hour,time,current,voltage,power,pressure_anode_inlet,pressure_anode_outlet,pressure_cathode_inlet,pressure_cathode_outlet,temp_anode_endplate,temp_anode_dewpoint_water,temp_anode_inlet,temp_anode_outlet,temp_cathode_dewpoint_water,temp_cathode_inlet,temp_cathode_outlet,total_anode_stack_flow,total_cathode_stack_flow
0,50,s,A,V,W,kPag,kPag,kPag,kPag,°C,°C,°C,°C,°C,°C,°C,NLPM,NLPM
1,50,Elapsed time,current,voltage,power,pressure_anode_inlet,pressure_anode_outlet,pressure_cathode_inlet,pressure_cathode_outlet,temp_anode_endplate,temp_anode_dewpoint_water,temp_anode_inlet,temp_anode_outlet,temp_cathode_dewpoint_water,temp_cathode_inlet,temp_cathode_outlet,total_anode_stack_flow,total_cathode_stack_flow
2,50,1.761,0,0.9375,0,109.901303,110.32725,109.800128,108.792114,83.128159,54.464745,71.951462,39.453175,64.464287,69.673592,56.337543,0.07,0.291
3,50,2.761,0,0.9375,0,110.103653,110.32725,109.800128,108.893387,83.078773,54.464745,71.902084,39.387039,64.439034,69.661247,56.324917,0.07,0.291
4,50,3.761,0,0.9372,0,110.306003,110.32725,109.800128,108.792114,83.078773,54.529343,71.88974,39.41349,64.486618,69.685936,56.299664,0.07,0.291

In [ ]:
### Remove Metadata Rows

Each operational dataset contains two metadata rows immediately following the header row. These rows describe the measurement units and variable names rather than representing experimental observations.

Using the `operating_hour` identifier, the first two rows of every operating-hour experiment are removed while preserving all genuine experimental measurements.

This approach ensures that:

- the same cleaning procedure is applied consistently to every experiment;
- no valid observations are removed;
- the integrity of the merged dataset is maintained.

In [16]:
metadata_rows = (
    cleaned_dataset
    .groupby("operating_hour")
    .cumcount() < 2
)

cleaned_dataset = cleaned_dataset.loc[~metadata_rows].reset_index(drop=True)

print("Metadata rows removed successfully.")
print(cleaned_dataset.shape)

Metadata rows removed successfully.
(3629680, 18)

In [ ]:
### Verify Metadata Removal

After removing the metadata rows, the dataset is verified to ensure that:

- two rows have been removed from each operating-hour experiment;
- the first remaining row of each experiment is a genuine experimental observation;
- the total number of observations has decreased only by the expected amount.

In [17]:
# ============================================================
# Verify Metadata Removal
# ============================================================

print("Dataset shape after metadata removal:")
print(cleaned_dataset.shape)

print("\n")

print("First five rows of the 50-hour experiment:")

cleaned_dataset.loc[
    cleaned_dataset["operating_hour"] == 50
].head()

Dataset shape after metadata removal:
(3629680, 18)


First five rows of the 50-hour experiment:

,operating_hour,time,current,voltage,power,pressure_anode_inlet,pressure_anode_outlet,pressure_cathode_inlet,pressure_cathode_outlet,temp_anode_endplate,temp_anode_dewpoint_water,temp_anode_inlet,temp_anode_outlet,temp_cathode_dewpoint_water,temp_cathode_inlet,temp_cathode_outlet,total_anode_stack_flow,total_cathode_stack_flow
0,50,1.761,0,0.9375,0,109.901303,110.32725,109.800128,108.792114,83.128159,54.464745,71.951462,39.453175,64.464287,69.673592,56.337543,0.07,0.291
1,50,2.761,0,0.9375,0,110.103653,110.32725,109.800128,108.893387,83.078773,54.464745,71.902084,39.387039,64.439034,69.661247,56.324917,0.07,0.291
2,50,3.761,0,0.9372,0,110.306003,110.32725,109.800128,108.792114,83.078773,54.529343,71.88974,39.41349,64.486618,69.685936,56.299664,0.07,0.291
3,50,4.761,0,0.9375,0,110.103653,110.32725,109.800128,108.792114,83.103462,54.477665,71.939117,39.387039,64.439034,69.685936,56.324917,0.07,0.291
4,50,5.761,0,0.9372,0,109.901303,110.32725,109.698953,108.893387,83.091118,54.477665,71.88974,39.37381,64.489532,69.661247,56.249161,0.07,0.291

In [ ]:
### Verify Structural Cleaning

Following the removal of the metadata rows, the integrity of each operating-hour experiment is verified.

The verification confirms that:

- every experiment remains present in the cleaned dataset;
- exactly two metadata rows have been removed from each experiment;
- the remaining observations correspond only to genuine experimental measurements;
- the `operating_hour` identifier has been preserved correctly.

This verification provides confidence that the cleaning procedure has been applied consistently across all operational datasets without affecting the recorded experimental observations.

In [18]:
# ============================================================
# Verify Number of Observations per Operating-Hour Experiment
# ============================================================

rows_per_experiment = (
    cleaned_dataset
    .groupby("operating_hour")
    .size()
    .reset_index(name="row_count")
)

rows_per_experiment

    operating_hour  row_count
0               50     179360
1              100     179360
2              150     179360
3              200     179360
4              250     179360
5              300     179360
6              350     179360
7              400     179360
8              450     179360
9              500     179360
10             550     179360
11             600     179360
12             650     179360
13             700     179360
14             750     179360
15             800     179360
16             850     179360
17             900     179360
18             950     179360
19            1000     221840

In [19]:
# ============================================================
# Verify Expected Row Counts
# ============================================================

expected_rows = {
    50: 179360,
    100: 179360,
    150: 179360,
    200: 179360,
    250: 179360,
    300: 179360,
    350: 179360,
    400: 179360,
    450: 179360,
    500: 179360,
    550: 179360,
    600: 179360,
    650: 179360,
    700: 179360,
    750: 179360,
    800: 179360,
    850: 179360,
    900: 179360,
    950: 179360,
    1000: 221840
}

verification = rows_per_experiment.copy()

verification["expected_rows"] = verification["operating_hour"].map(expected_rows)

verification["verification"] = (
    verification["row_count"] ==
    verification["expected_rows"]
)

verification

    operating_hour  row_count  expected_rows  verification
0               50     179360         179360          True
1              100     179360         179360          True
2              150     179360         179360          True
3              200     179360         179360          True
4              250     179360         179360          True
5              300     179360         179360          True
6              350     179360         179360          True
7              400     179360         179360          True
8              450     179360         179360          True
9              500     179360         179360          True
10             550     179360         179360          True
11             600     179360         179360          True
12             650     179360         179360          True
13             700     179360         179360          True
14             750     179360         179360          True
15             800     179360         179360          True
16             850     179360         179360          True
17             900     179360         179360          True
18             950     179360         179360          True
19            1000     221840         221840          True

In [ ]:
## C5.2 Data Type Conversion

After removing the metadata rows, the operational measurements can now be converted from string/object data types into numerical data types.

This conversion is necessary because statistical analysis, exploratory data analysis, feature engineering, and machine learning algorithms require numerical input variables.

The `operating_hour` column is retained as an integer identifier, while all sensor and operational measurement variables are converted to numeric format.

In [20]:
# ============================================================
# C5.2 Data Type Conversion
# ============================================================

# Identify columns to convert to numeric
numeric_columns = [
    col for col in cleaned_dataset.columns
    if col != "operating_hour"
]

# Convert operational variables to numeric
for col in numeric_columns:
    cleaned_dataset[col] = pd.to_numeric(
        cleaned_dataset[col],
        errors="coerce"
    )

print("Data type conversion completed successfully.")

Data type conversion completed successfully.

In [21]:
# ============================================================
# Verify Data Types After Conversion
# ============================================================

cleaned_dataset.dtypes

operating_hour                   int64
time                           float64
current                        float64
voltage                        float64
power                          float64
pressure_anode_inlet           float64
pressure_anode_outlet          float64
pressure_cathode_inlet         float64
pressure_cathode_outlet        float64
temp_anode_endplate            float64
temp_anode_dewpoint_water      float64
temp_anode_inlet               float64
temp_anode_outlet              float64
temp_cathode_dewpoint_water    float64
temp_cathode_inlet             float64
temp_cathode_outlet            float64
total_anode_stack_flow         float64
total_cathode_stack_flow       float64
dtype: object

In [ ]:
### Verify Data Type Conversion

After converting the operational variables to numerical data types, it is important to verify that the conversion was successful.

Because the conversion was performed using `errors='coerce'`, any values that could not be interpreted as numerical measurements would have been converted to missing values (`NaN`).

The following verification confirms that:

- all operational variables have been converted successfully;
- no unexpected missing values have been introduced during the conversion;
- the dataset remains suitable for subsequent analysis.

In [22]:
# ============================================================
# Verify Missing Values After Data Type Conversion
# ============================================================

missing_after_conversion = (
    cleaned_dataset
    .isnull()
    .sum()
    .reset_index()
)

missing_after_conversion.columns = [
    "Variable",
    "Missing Values"
]

missing_after_conversion

                       Variable  Missing Values
0                operating_hour               0
1                          time               0
2                       current               0
3                       voltage               0
4                         power               0
5          pressure_anode_inlet               0
6         pressure_anode_outlet               0
7        pressure_cathode_inlet               0
8       pressure_cathode_outlet               0
9           temp_anode_endplate               0
10    temp_anode_dewpoint_water               0
11             temp_anode_inlet               0
12            temp_anode_outlet               0
13  temp_cathode_dewpoint_water               0
14           temp_cathode_inlet               0
15          temp_cathode_outlet               0
16       total_anode_stack_flow               0
17     total_cathode_stack_flow               0

In [23]:
# ============================================================
# Verify Successful Numeric Conversion
# ============================================================

if cleaned_dataset.isnull().sum().sum() == 0:
    print("✓ Data type conversion completed successfully.")
    print("✓ No missing values were introduced.")
else:
    print("⚠ Missing values detected after conversion.")

✓ Data type conversion completed successfully.
✓ No missing values were introduced.

In [ ]:
## C5.3 Cleaning Verification

Following the structural cleaning and data type conversion procedures, the cleaned dataset is verified to ensure that all transformations have been applied correctly.

The verification confirms that:

- the dataset dimensions are as expected;
- all variables have appropriate data types;
- no unexpected missing values were introduced;
- all operating-hour experiments remain present;
- the cleaned dataset accurately represents the original experimental observations.

These verification steps provide confidence that the dataset is ready for subsequent data quality assessment and exploratory analysis.

In [ ]:
### Verify Dataset Dimensions

The overall dimensions of the cleaned dataset are verified to ensure that the expected number of observations and variables remain after the cleaning process.

In [24]:
# ============================================================
# Verify Dataset Dimensions
# ============================================================

print("Rows :", cleaned_dataset.shape[0])
print("Columns :", cleaned_dataset.shape[1])

Rows : 3629680
Columns : 18

In [ ]:
### Verify Data Types

The data types of every variable are reviewed to confirm that all operational measurements have been converted to appropriate numerical formats while preserving the experimental identifier.

In [25]:
# ============================================================
# Verify Data Types
# ============================================================

cleaned_dataset.dtypes

operating_hour                   int64
time                           float64
current                        float64
voltage                        float64
power                          float64
pressure_anode_inlet           float64
pressure_anode_outlet          float64
pressure_cathode_inlet         float64
pressure_cathode_outlet        float64
temp_anode_endplate            float64
temp_anode_dewpoint_water      float64
temp_anode_inlet               float64
temp_anode_outlet              float64
temp_cathode_dewpoint_water    float64
temp_cathode_inlet             float64
temp_cathode_outlet            float64
total_anode_stack_flow         float64
total_cathode_stack_flow       float64
dtype: object

In [ ]:
### Verify Missing Values

The cleaned dataset is examined for missing values to ensure that the data type conversion process has not introduced any unexpected missing observations.

In [26]:
# ============================================================
# Verify Missing Values
# ============================================================

missing_summary = pd.DataFrame({

    "Variable": cleaned_dataset.columns,

    "Missing Values": cleaned_dataset.isnull().sum().values

})

missing_summary

                       Variable  Missing Values
0                operating_hour               0
1                          time               0
2                       current               0
3                       voltage               0
4                         power               0
5          pressure_anode_inlet               0
6         pressure_anode_outlet               0
7        pressure_cathode_inlet               0
8       pressure_cathode_outlet               0
9           temp_anode_endplate               0
10    temp_anode_dewpoint_water               0
11             temp_anode_inlet               0
12            temp_anode_outlet               0
13  temp_cathode_dewpoint_water               0
14           temp_cathode_inlet               0
15          temp_cathode_outlet               0
16       total_anode_stack_flow               0
17     total_cathode_stack_flow               0

In [27]:
# ============================================================
# Overall Missing Value Verification
# ============================================================

total_missing = cleaned_dataset.isnull().sum().sum()

print("Total Missing Values:", total_missing)

if total_missing == 0:
    print("✓ No missing values detected.")
else:
    print("⚠ Missing values detected.")

Total Missing Values: 0
✓ No missing values detected.

In [ ]:
### Verify Operating-Hour Experiments

The cleaned dataset is examined to confirm that all operating-hour experiments remain present and that the experimental identities have been preserved throughout the cleaning process.

In [28]:
# ============================================================
# Verify Operating-Hour Experiments
# ============================================================

experiment_summary = (

    cleaned_dataset

    .groupby("operating_hour")

    .size()

    .reset_index(name="row_count")

)

experiment_summary

    operating_hour  row_count
0               50     179360
1              100     179360
2              150     179360
3              200     179360
4              250     179360
5              300     179360
6              350     179360
7              400     179360
8              450     179360
9              500     179360
10             550     179360
11             600     179360
12             650     179360
13             700     179360
14             750     179360
15             800     179360
16             850     179360
17             900     179360
18             950     179360
19            1000     221840

In [ ]:
### Verify Numerical Variables

The cleaned dataset is examined to confirm that all operational measurement variables are now stored using numerical data types and are therefore suitable for statistical analysis and machine learning.

In [29]:
# ============================================================
# Verify Numerical Variables
# ============================================================

numeric_columns = cleaned_dataset.select_dtypes(include=["number"]).columns

print("Number of numerical variables:", len(numeric_columns))

print("\nNumerical variables:\n")

print(list(numeric_columns))

Number of numerical variables: 18

Numerical variables:

['operating_hour', 'time', 'current', 'voltage', 'power', 'pressure_anode_inlet', 'pressure_anode_outlet', 'pressure_cathode_inlet', 'pressure_cathode_outlet', 'temp_anode_endplate', 'temp_anode_dewpoint_water', 'temp_anode_inlet', 'temp_anode_outlet', 'temp_cathode_dewpoint_water', 'temp_cathode_inlet', 'temp_cathode_outlet', 'total_anode_stack_flow', 'total_cathode_stack_flow']

In [ ]:
### Cleaning Verification Summary

The verification procedures confirm that the cleaning process has been completed successfully.

The cleaned dataset:

- contains the expected number of observations and variables;
- retains all operating-hour experiments;
- contains appropriate numerical data types;
- contains no unexpected missing values;
- is ready for subsequent data quality assessment.

The cleaned dataset can therefore be considered analysis-ready for the next stage of the project.

In [ ]:
## C5.4 Save Cleaned Dataset

The cleaned operational dataset is saved for use throughout the remainder of the project.

Saving the cleaned dataset ensures that all subsequent notebooks begin from the same analysis-ready version of the data while preserving the original merged dataset for reproducibility.

In [30]:
# ============================================================
# Save Cleaned Operational Dataset
# ============================================================

output_path = PROCESSED_DATA_DIR / "operational_cleaned.csv"

cleaned_dataset.to_csv(
    output_path,
    index=False
)

print("Cleaned dataset saved successfully.")
print(output_path)

Cleaned dataset saved successfully.
C:\Users\usman\Desktop\PEMFC_Dissertation\data\processed\operational_cleaned.csv

In [ ]:
## C5.5 Summary and Initial Observations

The final cleaning summary provides an overview of the preprocessing operations performed and confirms the readiness of the cleaned dataset for subsequent analysis.

In [32]:
# ============================================================
# Cleaning Summary
# ============================================================

cleaning_summary = pd.DataFrame({

    "Metric": [
        "Total observations",
        "Total variables",
        "Operating-hour experiments",
        "Metadata rows removed",
        "Unnecessary columns removed",
        "Data type conversion",
        "Total missing values",
        "Dataset readiness"
    ],

    "Value": [
        f"{cleaned_dataset.shape[0]:,}",
        cleaned_dataset.shape[1],
        cleaned_dataset["operating_hour"].nunique(),
        "40 (2 rows × 20 operational datasets)",
        "1 (`Unnamed: 0`)",
        "17 variables converted from string/object to float64; operating_hour retained as int64",
        cleaned_dataset.isnull().sum().sum(),
        "Ready for Data Quality Assessment (Notebook 05)"
    ]

})

cleaning_summary

                        Metric                                                                                   Value
0           Total observations                                                                               3,629,680
1              Total variables                                                                                      18
2   Operating-hour experiments                                                                                      20
3        Metadata rows removed                                                   40 (2 rows × 20 operational datasets)
4  Unnecessary columns removed                                                                        1 (`Unnamed: 0`)
5         Data type conversion  17 variables converted from string/object to float64; operating_hour retained as int64
6         Total missing values                                                                                       0
7            Dataset readiness                                         Ready for Data Quality Assessment (Notebook 05)

In [ ]:
# Notebook Summary

This notebook successfully transformed the merged operational dataset into a clean, consistent, and analysis-ready dataset.

The following preprocessing steps were completed:

- Removed the unnecessary exported index column (`Unnamed: 0`).
- Removed two metadata rows from each of the twenty operational datasets.
- Preserved all genuine experimental observations and operating-hour identities.
- Converted all operational measurement variables from string/object format to appropriate numerical (`float64`) data types.
- Retained the `operating_hour` variable as an integer (`int64`) identifier.
- Verified dataset dimensions, variable data types, missing values, and experiment integrity.
- Saved the cleaned dataset as `operational_cleaned.csv`.

The cleaned dataset is now ready for the next phase of the project: **Data Quality Assessment (Notebook 05)**.