In [ ]:
# C7. Missing Values, Duplicates, Outliers, Sensor Spikes and Time-Series Integrity

## Objective

The objective of this notebook is to perform a comprehensive investigation of the cleaned operational dataset by examining missing values, duplicate observations, statistical outliers, sensor spikes, and the chronological integrity of the recorded time-series measurements.

Unlike the previous notebook, which assessed the overall quality of the dataset, this notebook investigates detailed data characteristics that may influence exploratory data analysis, feature engineering, statistical modelling, and machine learning.

The analyses performed in this notebook provide a deeper understanding of the dataset while preserving the original experimental observations.

In [ ]:
## Workflow

This notebook covers the following tasks:

1. Import required libraries
2. Configure display settings
3. Define project paths
4. Load the cleaned operational dataset
5. Investigate missing values
6. Investigate duplicate observations
7. Investigate statistical outliers
8. Investigate sensor spikes
9. Investigate time-series integrity
10. Generate the investigation summary
11. Record research insights
12. Transition to Exploratory Data Analysis

In [1]:
# ============================================================
# Import Required Libraries
# ============================================================

from pathlib import Path

import pandas as pd
import numpy as np

In [2]:
# ============================================================
# Configure Display Settings
# ============================================================

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 120)
pd.set_option("display.max_colwidth", None)

In [3]:
# ============================================================
# Define Project Paths
# ============================================================

PROJECT_ROOT = Path.cwd().parent

PROCESSED_DATA_DIR = PROJECT_ROOT / "data" / "processed"

print("Project Root:", PROJECT_ROOT)
print("Processed Data Folder:", PROCESSED_DATA_DIR)

Project Root: C:\Users\usman\Desktop\PEMFC_Dissertation
Processed Data Folder: C:\Users\usman\Desktop\PEMFC_Dissertation\data\processed

In [ ]:
## C7.1 Load the Cleaned Operational Dataset

The cleaned operational dataset produced in Notebook 04 is loaded for detailed data investigation.

This notebook does not modify the dataset. Instead, it investigates potential data quality characteristics that may influence subsequent exploratory analysis and predictive modelling.

In [4]:
# ============================================================
# Load Cleaned Operational Dataset
# ============================================================

cleaned_dataset = pd.read_csv(
    PROCESSED_DATA_DIR / "operational_cleaned.csv",
    low_memory=False
)

print("Cleaned operational dataset loaded successfully.")

Cleaned operational dataset loaded successfully.

In [ ]:
## C7.1.1 Verify Successful Loading

Before beginning the detailed investigation, the cleaned operational dataset is verified to ensure that the expected number of observations, variables, and operating-hour experiments have been preserved.

This verification confirms that the correct version of the dataset is being used throughout this notebook.

In [5]:
# ============================================================
# Verify Successful Dataset Loading
# ============================================================

loading_summary = pd.DataFrame({

    "Metric": [
        "Total observations",
        "Total variables",
        "Operating-hour experiments"
    ],

    "Value": [
        f"{cleaned_dataset.shape[0]:,}",
        cleaned_dataset.shape[1],
        cleaned_dataset["operating_hour"].nunique()
    ]

})

loading_summary

                       Metric      Value
0          Total observations  3,629,680
1             Total variables         18
2  Operating-hour experiments         20

In [ ]:
## C7.1.2 Research Insight

### Observation

The cleaned operational dataset was successfully loaded and matches the expected dimensions produced during the data cleaning stage.

### Why is this important?

Verifying the dataset before beginning a detailed investigation ensures that all subsequent analyses are performed on the correct version of the data.

### Engineering Interpretation

The complete set of twenty operating-hour experiments has been preserved, ensuring that degradation behaviour can be investigated consistently across the full experimental duration.

### Dissertation Interpretation

The preprocessing workflow has successfully preserved the experimental structure established during the original durability tests. This provides confidence that the forthcoming analyses accurately represent the underlying PEM fuel cell experiments.

### Decision

No further preprocessing is required at this stage. The cleaned dataset will now undergo detailed investigation of missing values, duplicate observations, statistical outliers, sensor behaviour, and time-series integrity.

In [ ]:
## C7.2 Missing Value Investigation

Missing values are one of the most common data quality issues encountered in data science and time-series analysis.

Although the previous notebook confirmed that the cleaned operational dataset is complete, this section performs a detailed investigation to verify the distribution of missing values across the entire dataset, individual variables, and operating-hour experiments.

This investigation provides documented evidence that the dataset can be used for subsequent statistical analysis and machine learning without requiring missing value imputation.

In [ ]:
### Overall Missing Value Investigation

The overall number and percentage of missing values are calculated to provide a high-level assessment of data completeness.

This serves as the starting point for the detailed missing value investigation.

In [6]:
# ============================================================
# Overall Missing Value Investigation
# ============================================================

total_cells = cleaned_dataset.size

missing_cells = cleaned_dataset.isnull().sum().sum()

missing_percentage = (
    missing_cells / total_cells
) * 100

overall_missing_summary = pd.DataFrame({

    "Metric": [
        "Total cells",
        "Missing cells",
        "Missing percentage (%)"
    ],

    "Value": [
        f"{total_cells:,}",
        f"{missing_cells:,}",
        f"{missing_percentage:.4f}%"
    ]

})

overall_missing_summary

                   Metric       Value
0             Total cells  65,334,240
1           Missing cells           0
2  Missing percentage (%)     0.0000%

In [ ]:
### Missing Values by Variable

The number and percentage of missing values are calculated for every variable in the cleaned operational dataset.

This investigation identifies whether any individual measurement variable contains incomplete observations.

In [7]:
# ============================================================
# Missing Values by Variable
# ============================================================

variable_missing = pd.DataFrame({

    "Variable": cleaned_dataset.columns,

    "Missing Values": cleaned_dataset.isnull().sum().values

})

variable_missing["Missing Percentage (%)"] = (

    variable_missing["Missing Values"]

    /

    len(cleaned_dataset)

) * 100

variable_missing = variable_missing.sort_values(
    by="Missing Values",
    ascending=False
).reset_index(drop=True)

variable_missing

                       Variable  Missing Values  Missing Percentage (%)
0                operating_hour               0                     0.0
1                          time               0                     0.0
2                       current               0                     0.0
3                       voltage               0                     0.0
4                         power               0                     0.0
5          pressure_anode_inlet               0                     0.0
6         pressure_anode_outlet               0                     0.0
7        pressure_cathode_inlet               0                     0.0
8       pressure_cathode_outlet               0                     0.0
9           temp_anode_endplate               0                     0.0
10    temp_anode_dewpoint_water               0                     0.0
11             temp_anode_inlet               0                     0.0
12            temp_anode_outlet               0                     0.0
13  temp_cathode_dewpoint_water               0                     0.0
14           temp_cathode_inlet               0                     0.0
15          temp_cathode_outlet               0                     0.0
16       total_anode_stack_flow               0                     0.0
17     total_cathode_stack_flow               0                     0.0

In [ ]:
### Missing Values by Operating-Hour Experiment

The distribution of missing values is examined for each operating-hour experiment.

This assessment verifies whether any individual durability experiment contains incomplete observations.

In [8]:
# ============================================================
# Missing Values by Operating-Hour Experiment
# ============================================================

experiment_missing = (

    cleaned_dataset

    .groupby("operating_hour")

    .apply(

        lambda df: pd.Series({

            "Observations": len(df),

            "Missing Values": df.isnull().sum().sum(),

            "Missing Percentage (%)": (

                df.isnull().sum().sum()

                /

                df.size

            ) * 100

        })

    )

    .reset_index()

)

experiment_missing

    operating_hour  Observations  Missing Values  Missing Percentage (%)
0               50      179360.0             0.0                     0.0
1              100      179360.0             0.0                     0.0
2              150      179360.0             0.0                     0.0
3              200      179360.0             0.0                     0.0
4              250      179360.0             0.0                     0.0
5              300      179360.0             0.0                     0.0
6              350      179360.0             0.0                     0.0
7              400      179360.0             0.0                     0.0
8              450      179360.0             0.0                     0.0
9              500      179360.0             0.0                     0.0
10             550      179360.0             0.0                     0.0
11             600      179360.0             0.0                     0.0
12             650      179360.0             0.0                     0.0
13             700      179360.0             0.0                     0.0
14             750      179360.0             0.0                     0.0
15             800      179360.0             0.0                     0.0
16             850      179360.0             0.0                     0.0
17             900      179360.0             0.0                     0.0
18             950      179360.0             0.0                     0.0
19            1000      221840.0             0.0                     0.0

In [ ]:
### Missing Value Summary

The results of the missing value investigation are summarised to provide an overall assessment of missing data within the cleaned operational dataset.

In [9]:
# ============================================================
# Missing Value Summary
# ============================================================

variables_with_missing = (
    variable_missing["Missing Values"] > 0
).sum()

experiments_with_missing = (
    experiment_missing["Missing Values"] > 0
).sum()

missing_summary = pd.DataFrame({

    "Metric": [

        "Overall missing values",
        "Variables with missing values",
        "Experiments with missing values",
        "Missing value status",
        "Dataset readiness"

    ],

    "Value": [

        f"{missing_cells:,}",
        variables_with_missing,
        experiments_with_missing,
        "No missing values detected"
            if missing_cells == 0
            else "Missing values detected",
        "Ready for Duplicate Investigation (C7.3)"

    ]

})

missing_summary

                            Metric                                     Value
0           Overall missing values                                         0
1    Variables with missing values                                         0
2  Experiments with missing values                                         0
3             Missing value status                No missing values detected
4                Dataset readiness  Ready for Duplicate Investigation (C7.3)

In [ ]:
## Research Insight

### Observation

No missing values were identified within the cleaned operational dataset. All variables and operating-hour experiments contain complete observations.

### Why is this important?

Complete datasets eliminate the need for missing value imputation, reducing the risk of introducing artificial patterns or uncertainty into subsequent analyses.

### Engineering Interpretation

The absence of missing sensor measurements indicates that the controlled PEM fuel cell durability experiments were recorded consistently throughout the testing period. This suggests stable data acquisition and reliable experimental logging.

### Dissertation Interpretation

The complete dataset provides a strong foundation for exploratory data analysis, feature engineering, and predictive modelling. Since no missing values are present, all analyses can be performed using the original experimental observations without additional preprocessing.

### Decision

No missing value treatment is required. The dataset will be carried forward unchanged to the duplicate observation investigation.

In [ ]:
## C7.3 Duplicate Observation Investigation

Duplicate observations occur when identical records appear more than once within a dataset.

In time-series datasets, duplicate records may result from repeated logging, system restarts, data export procedures, or genuine repeated operating conditions. Therefore, duplicate observations should be investigated carefully before deciding whether they require removal.

The objective of this section is to identify duplicate observations, investigate their distribution across operating-hour experiments, and determine whether duplicate timestamps are present within the recorded time-series.

In [ ]:
### Overall Duplicate Observation Investigation

The cleaned operational dataset is examined to determine the total number and percentage of duplicate observations.

This provides an initial indication of whether duplicate records are present within the dataset.

In [10]:
# ============================================================
# Overall Duplicate Observation Investigation
# ============================================================

duplicate_rows = cleaned_dataset.duplicated().sum()

duplicate_percentage = (
    duplicate_rows / len(cleaned_dataset)
) * 100

overall_duplicate_summary = pd.DataFrame({

    "Metric": [
        "Total observations",
        "Duplicate observations",
        "Duplicate percentage (%)"
    ],

    "Value": [
        f"{len(cleaned_dataset):,}",
        f"{duplicate_rows:,}",
        f"{duplicate_percentage:.4f}%"
    ]

})

overall_duplicate_summary

                     Metric      Value
0        Total observations  3,629,680
1    Duplicate observations          0
2  Duplicate percentage (%)    0.0000%

In [ ]:
### Duplicate Observations by Operating-Hour Experiment

Duplicate observations are examined separately for each operating-hour experiment.

This assessment determines whether duplicate records are concentrated within specific experiments or distributed uniformly throughout the dataset.

In [11]:
# ============================================================
# Duplicate Observations by Operating-Hour Experiment
# ============================================================

duplicate_by_experiment = (

    cleaned_dataset

    .groupby("operating_hour")

    .apply(

        lambda df: pd.Series({

            "Observations": len(df),

            "Duplicate Observations": df.duplicated().sum()

        })

    )

    .reset_index()

)

duplicate_by_experiment["Duplicate Percentage (%)"] = (

    duplicate_by_experiment["Duplicate Observations"]

    /

    duplicate_by_experiment["Observations"]

) * 100

duplicate_by_experiment

    operating_hour  Observations  Duplicate Observations  Duplicate Percentage (%)
0               50        179360                       0                       0.0
1              100        179360                       0                       0.0
2              150        179360                       0                       0.0
3              200        179360                       0                       0.0
4              250        179360                       0                       0.0
5              300        179360                       0                       0.0
6              350        179360                       0                       0.0
7              400        179360                       0                       0.0
8              450        179360                       0                       0.0
9              500        179360                       0                       0.0
10             550        179360                       0                       0.0
11             600        179360                       0                       0.0
12             650        179360                       0                       0.0
13             700        179360                       0                       0.0
14             750        179360                       0                       0.0
15             800        179360                       0                       0.0
16             850        179360                       0                       0.0
17             900        179360                       0                       0.0
18             950        179360                       0                       0.0
19            1000        221840                       0                       0.0

In [ ]:
### Duplicate Timestamp Investigation

The recorded timestamps are examined within each operating-hour experiment to identify duplicate time values.

Duplicate timestamps may indicate repeated logging events, acquisition artefacts, or intentional repeated measurements and should therefore be investigated separately from duplicate observations.

In [12]:
# ============================================================
# Duplicate Timestamp Investigation
# ============================================================

duplicate_timestamps = (

    cleaned_dataset

    .groupby("operating_hour")["time"]

    .apply(lambda x: x.duplicated().sum())

    .reset_index(name="Duplicate Timestamps")

)

duplicate_timestamps

    operating_hour  Duplicate Timestamps
0               50                     0
1              100                     0
2              150                     0
3              200                     0
4              250                     0
5              300                     0
6              350                     0
7              400                     0
8              450                     0
9              500                     0
10             550                     0
11             600                     0
12             650                     0
13             700                     0
14             750                     0
15             800                     0
16             850                     0
17             900                     0
18             950                     0
19            1000                     0

In [ ]:
### Duplicate Investigation Summary

The results of the duplicate investigation are summarised to provide an overall assessment of duplicate observations and duplicate timestamps within the cleaned operational dataset.

In [13]:
# ============================================================
# Duplicate Investigation Summary
# ============================================================

duplicate_summary = pd.DataFrame({

    "Metric":[

        "Duplicate observations",

        "Experiments containing duplicate observations",

        "Duplicate timestamps",

        "Duplicate investigation status",

        "Dataset readiness"

    ],

    "Value":[

        f"{duplicate_rows:,}",

        (duplicate_by_experiment["Duplicate Observations"] > 0).sum(),

        duplicate_timestamps["Duplicate Timestamps"].sum(),

        "No duplicate observations detected"
        if duplicate_rows == 0
        else "Duplicate observations detected",

        "Ready for Statistical Outlier Investigation (C7.4)"

    ]

})

duplicate_summary

                                          Metric                                               Value
0                         Duplicate observations                                                   0
1  Experiments containing duplicate observations                                                   0
2                           Duplicate timestamps                                                   0
3                 Duplicate investigation status                  No duplicate observations detected
4                              Dataset readiness  Ready for Statistical Outlier Investigation (C7.4)

In [ ]:
## C7.3.5 Research Insight

### Observation

The duplicate investigation identified no duplicate observations or duplicate timestamps within the cleaned operational dataset. Every operating-hour experiment contains a unique sequence of observations, and each timestamp represents a distinct measurement event.

### Why is this important?

Duplicate observations can introduce bias into descriptive statistics, correlation analysis, feature engineering, and predictive modelling by artificially increasing the influence of repeated measurements. Similarly, duplicate timestamps may indicate data logging artefacts or acquisition errors that can compromise time-series analyses.

### Engineering Interpretation

The absence of duplicate observations and duplicate timestamps indicates that the PEM fuel cell durability experiments were recorded consistently throughout the testing period. Each sensor measurement represents a unique operating condition, suggesting that the data acquisition system functioned reliably without repeated logging or timestamp conflicts.

### Dissertation Interpretation

The duplicate investigation provides further evidence that the cleaned operational dataset maintains a high level of quality and accurately represents the original experimental measurements. Since no duplicate records are present, subsequent analyses can be performed using the complete dataset without requiring duplicate removal or correction.

### Decision

No duplicate observations or duplicate timestamps require further processing. The dataset will be carried forward unchanged to the statistical outlier investigation.

In [ ]:
## C7.4 Statistical Outlier Investigation

Outliers are observations that differ substantially from the majority of the recorded measurements.

In engineering datasets, outliers are not necessarily errors. They may represent unusual operating conditions, transient system behaviour, degradation effects, sensor noise, or genuine physical phenomena.

The objective of this section is to identify statistically unusual observations using two complementary approaches:

- Interquartile Range (IQR)
- Z-score Analysis

The identified observations will be documented for further interpretation rather than removed from the dataset.

In [ ]:
### Interquartile Range (IQR) Investigation

The Interquartile Range method is used to identify observations that fall substantially outside the central 50% of the recorded measurements.

For each operational variable, lower and upper thresholds are calculated using the 1.5 × IQR rule, and the number of observations outside these limits is recorded.

In [14]:
# ============================================================
# Interquartile Range (IQR) Investigation
# ============================================================

numerical_columns = cleaned_dataset.select_dtypes(
    include="number"
).columns.tolist()

# Remove identifier
numerical_columns.remove("operating_hour")

iqr_results = []

for column in numerical_columns:

    Q1 = cleaned_dataset[column].quantile(0.25)
    Q3 = cleaned_dataset[column].quantile(0.75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = (
        (cleaned_dataset[column] < lower) |
        (cleaned_dataset[column] > upper)
    ).sum()

    iqr_results.append({

        "Variable": column,
        "Q1": round(Q1,4),
        "Q3": round(Q3,4),
        "Lower Bound": round(lower,4),
        "Upper Bound": round(upper,4),
        "Outliers": outliers,
        "Percentage (%)": round(
            outliers / len(cleaned_dataset) * 100,
            4
        )

    })

iqr_summary = pd.DataFrame(iqr_results)

iqr_summary

                       Variable          Q1           Q3  Lower Bound  Upper Bound  Outliers  Percentage (%)
0                          time  45372.0390  136113.8650  -90740.7000  272226.6040         0          0.0000
1                       current      1.7604      14.8163     -17.8234      34.4001    135333          3.7285
2                       voltage      0.6871       0.8428       0.4536       1.0764         4          0.0001
3                         power      1.4900      10.3300     -11.7700      23.5900         0          0.0000
4          pressure_anode_inlet    109.9013     110.2048     109.4460     110.6601    280556          7.7295
5         pressure_anode_outlet    110.0239     110.4284     109.4173     111.0350    302492          8.3338
6        pressure_cathode_inlet    109.3954     110.5084     107.7260     112.1777    315950          8.7046
7       pressure_cathode_outlet    107.0705     108.7921     104.4880     111.3746    217194          5.9838
8           temp_anode_endplate     82.9359      83.7908      81.6535      85.0732       128          0.0035
9     temp_anode_dewpoint_water     54.9457      55.0298      54.8196      55.1560    588599         16.2163
10             temp_anode_inlet     69.7354      70.1880      69.0567      70.8667    179924          4.9570
11            temp_anode_outlet     37.2700      45.2698      25.2703      57.2695       819          0.0226
12  temp_cathode_dewpoint_water     64.8940      65.0587      64.6469      65.3058    321951          8.8700
13           temp_cathode_inlet     69.3884      70.6336      67.5206      72.5014       229          0.0063
14          temp_cathode_outlet     53.9469      58.0428      47.8030      64.1867     13000          0.3582
15       total_anode_stack_flow      0.0840       0.2070      -0.1005       0.3915    287327          7.9160
16     total_cathode_stack_flow      0.3490       0.8640      -0.4235       1.6365    287315          7.9157

In [ ]:
### Z-score Investigation

The Z-score method identifies observations located more than three standard deviations from the mean.

This provides a complementary assessment of statistical outliers and allows comparison with the Interquartile Range method.

In [16]:
# ============================================================
# Z-score Investigation
# ============================================================

zscore_results = []

for column in numerical_columns:

    mean = cleaned_dataset[column].mean()
    std = cleaned_dataset[column].std()

    z_scores = (
        cleaned_dataset[column] - mean
    ) / std

    outliers = (
        np.abs(z_scores) > 3
    ).sum()

    zscore_results.append({

        "Variable": column,
        "Mean": round(mean,4),
        "Std Dev": round(std,4),
        "Outliers": outliers,
        "Percentage (%)": round(
            outliers / len(cleaned_dataset) * 100,
            4
        )

    })

zscore_summary = pd.DataFrame(zscore_results)

zscore_summary

                       Variable        Mean     Std Dev  Outliers  Percentage (%)
0                          time  90979.1379  52853.8083         0          0.0000
1                       current      9.9364      9.3921         0          0.0000
2                       voltage      0.7567      0.0972         5          0.0001
3                         power      6.6330      5.4652         0          0.0000
4          pressure_anode_inlet    109.9550      1.2382     25114          0.6919
5         pressure_anode_outlet    110.1856      1.2641     23719          0.6535
6        pressure_cathode_inlet    109.8189      1.4904    104118          2.8685
7       pressure_cathode_outlet    107.7650      1.5971     81688          2.2506
8           temp_anode_endplate     83.4078      0.5537       361          0.0099
9     temp_anode_dewpoint_water     54.9523      0.2086     91366          2.5172
10             temp_anode_inlet     69.9828      0.4368     51456          1.4176
11            temp_anode_outlet     41.0738      5.7043       186          0.0051
12  temp_cathode_dewpoint_water     64.9552      0.2372     58875          1.6220
13           temp_cathode_inlet     69.9927      0.7835       301          0.0083
14          temp_cathode_outlet     55.9852      2.9541      3317          0.0914
15       total_anode_stack_flow      0.1656      0.1099    132006          3.6368
16     total_cathode_stack_flow      0.6902      0.4587    132031          3.6375

In [ ]:
### Comparison of Outlier Detection Methods

The number of statistical outliers identified by the Interquartile Range and Z-score methods are compared for each operational variable.

This comparison highlights variables that consistently exhibit unusual behaviour across different statistical detection techniques.

In [17]:
# ============================================================
# Compare IQR and Z-score Results
# ============================================================

comparison = pd.DataFrame({

    "Variable": numerical_columns,

    "IQR Outliers":
        iqr_summary["Outliers"],

    "IQR Percentage (%)":
        iqr_summary["Percentage (%)"],

    "Z-score Outliers":
        zscore_summary["Outliers"],

    "Z-score Percentage (%)":
        zscore_summary["Percentage (%)"]

})

comparison

                       Variable  IQR Outliers  IQR Percentage (%)  Z-score Outliers  Z-score Percentage (%)
0                          time             0              0.0000                 0                  0.0000
1                       current        135333              3.7285                 0                  0.0000
2                       voltage             4              0.0001                 5                  0.0001
3                         power             0              0.0000                 0                  0.0000
4          pressure_anode_inlet        280556              7.7295             25114                  0.6919
5         pressure_anode_outlet        302492              8.3338             23719                  0.6535
6        pressure_cathode_inlet        315950              8.7046            104118                  2.8685
7       pressure_cathode_outlet        217194              5.9838             81688                  2.2506
8           temp_anode_endplate           128              0.0035               361                  0.0099
9     temp_anode_dewpoint_water        588599             16.2163             91366                  2.5172
10             temp_anode_inlet        179924              4.9570             51456                  1.4176
11            temp_anode_outlet           819              0.0226               186                  0.0051
12  temp_cathode_dewpoint_water        321951              8.8700             58875                  1.6220
13           temp_cathode_inlet           229              0.0063               301                  0.0083
14          temp_cathode_outlet         13000              0.3582              3317                  0.0914
15       total_anode_stack_flow        287327              7.9160            132006                  3.6368
16     total_cathode_stack_flow        287315              7.9157            132031                  3.6375

In [ ]:
### Outlier Investigation Summary

The statistical outlier investigation summarises the observations identified by both detection methods.

These observations are retained within the dataset because they may represent genuine engineering behaviour rather than erroneous measurements.

In [18]:
# ============================================================
# Outlier Investigation Summary
# ============================================================

outlier_summary = pd.DataFrame({

    "Metric":[

        "Variables assessed",

        "IQR method",

        "Z-score method",

        "Dataset readiness"

    ],

    "Value":[

        len(numerical_columns),

        "Completed",

        "Completed",

        "Ready for Sensor Spike Investigation (C7.5)"

    ]

})

outlier_summary

               Metric                                        Value
0  Variables assessed                                           17
1          IQR method                                    Completed
2      Z-score method                                    Completed
3   Dataset readiness  Ready for Sensor Spike Investigation (C7.5)

In [ ]:
## C7.4.5 Research Insight

### Observation

The statistical outlier investigation identified substantial differences between the Interquartile Range (IQR) and Z-score detection methods. The IQR method consistently identified a larger number of outliers than the Z-score method, particularly for pressure, dewpoint temperature, and reactant flow variables. In contrast, voltage and power contained very few statistically unusual observations.

### Why is this important?

Different statistical outlier detection methods respond differently to the underlying distribution of the data. The larger number of IQR outliers suggests that several operational variables exhibit skewed or non-normal distributions rather than measurement errors. Using multiple detection methods provides a more comprehensive understanding of the dataset and reduces the risk of incorrectly classifying valid observations as anomalies.

### Engineering Interpretation

The large number of statistical outliers observed in pressure, humidity (dewpoint), and reactant flow variables is consistent with the dynamic operating conditions of PEM fuel cell durability experiments. These variables naturally fluctuate in response to changes in reactant supply, water management, thermal regulation, and degradation processes. Conversely, the voltage variable exhibits remarkably few outliers, indicating relatively stable electrochemical behaviour throughout the experiments despite gradual performance degradation.

### Dissertation Interpretation

The statistical outlier investigation demonstrates that many unusual observations are likely to represent genuine operational behaviour rather than erroneous measurements. Consequently, statistical outliers should not be removed automatically. Instead, they should be retained for further investigation during exploratory data analysis and degradation behaviour analysis, where their physical significance can be evaluated within the operational context of the PEM fuel cell.

### Decision

No statistical outliers will be removed during this stage of the preprocessing workflow. All identified observations will be preserved for subsequent exploratory data analysis, where they will be interpreted in conjunction with operating conditions and degradation trends.

In [ ]:
## C7.5 Sensor Spike Investigation

Sensor spikes refer to sudden changes between consecutive measurements recorded during the operational experiments.

Unlike statistical outliers, which are identified from the overall distribution of the data, sensor spikes are detected by examining changes between successive observations in the time series.

This investigation helps identify abrupt measurement changes that may represent transient operating conditions, sensor artefacts, or genuine electrochemical behaviour.

In [ ]:
### First-Order Difference Calculation

The first-order difference measures the absolute change between consecutive observations for each operational variable.

Large first-order differences indicate sudden changes in the recorded measurements and are used as the basis for identifying potential sensor spikes.

In [19]:
# ============================================================
# Calculate First-Order Differences
# ============================================================

first_difference = cleaned_dataset.copy()

for column in numerical_columns:
    first_difference[column] = (
        cleaned_dataset
        .groupby("operating_hour")[column]
        .diff()
        .abs()
    )

print("First-order differences calculated successfully.")

First-order differences calculated successfully.

In [ ]:
### Largest Sensor Changes

The maximum first-order difference is calculated for each operational variable.

This identifies the largest observed change between consecutive measurements during the experiments.

In [20]:
# ============================================================
# Largest Sensor Changes
# ============================================================

largest_changes = pd.DataFrame({

    "Variable": numerical_columns,

    "Maximum Change": [

        first_difference[column].max()

        for column in numerical_columns

    ]

})

largest_changes = largest_changes.sort_values(
    by="Maximum Change",
    ascending=False
)

largest_changes

                       Variable  Maximum Change
4          pressure_anode_inlet       60.730271
5         pressure_anode_outlet       59.877493
1                       current       35.541500
3                         power       21.510000
11            temp_anode_outlet       18.568640
14          temp_cathode_outlet       12.692333
6        pressure_cathode_inlet        7.183422
7       pressure_cathode_outlet        5.481380
10             temp_anode_inlet        3.151039
13           temp_cathode_inlet        2.138428
16     total_cathode_stack_flow        1.753000
12  temp_cathode_dewpoint_water        1.649746
9     temp_anode_dewpoint_water        1.405601
0                          time        1.030000
2                       voltage        0.841100
8           temp_anode_endplate        0.611306
15       total_anode_stack_flow        0.420000

In [ ]:
### Potential Sensor Spike Candidates

Potential sensor spikes are identified using a variable-specific threshold based on the distribution of first-order differences.

For each variable, observations exceeding the mean plus three standard deviations of the first-order differences are identified as potential spike candidates.

In [21]:
# ============================================================
# Identify Potential Sensor Spikes
# ============================================================

spike_results = []

for column in numerical_columns:

    threshold = (
        first_difference[column].mean() +
        3 * first_difference[column].std()
    )

    spikes = (
        first_difference[column] > threshold
    ).sum()

    spike_results.append({

        "Variable": column,
        "Threshold": round(threshold, 4),
        "Spike Candidates": spikes,
        "Percentage (%)": round(
            spikes / len(cleaned_dataset) * 100,
            4
        )

    })

spike_summary = pd.DataFrame(spike_results)

spike_summary

                       Variable  Threshold  Spike Candidates  Percentage (%)
0                          time     1.0001               122          0.0034
1                       current     5.2823             67674          1.8645
2                       voltage     0.0688             61875          1.7047
3                         power     3.2085             60077          1.6552
4          pressure_anode_inlet     0.5321             26742          0.7368
5         pressure_anode_outlet     0.4770             19183          0.5285
6        pressure_cathode_inlet     0.6610             41077          1.1317
7       pressure_cathode_outlet     0.5957             65868          1.8147
8           temp_anode_endplate     0.1459             37135          1.0231
9     temp_anode_dewpoint_water     0.1207             33270          0.9166
10             temp_anode_inlet     0.1138             30635          0.8440
11            temp_anode_outlet     0.1321              8571          0.2361
12  temp_cathode_dewpoint_water     0.1061             38620          1.0640
13           temp_cathode_inlet     0.1189             47225          1.3011
14          temp_cathode_outlet     0.1692             38090          1.0494
15       total_anode_stack_flow     0.0455             55103          1.5181
16     total_cathode_stack_flow     0.1898             55493          1.5289

In [ ]:
### Sensor Spike Summary

The sensor spike investigation summarises the occurrence of sudden measurement changes across the operational variables.

Potential spike candidates are documented for further interpretation during exploratory data analysis rather than being treated as erroneous observations.

In [22]:
sensor_spike_summary = pd.DataFrame({

    "Metric":[

        "Variables investigated",

        "Spike detection method",

        "Total spike detections",

        "Variables containing spike candidates",

        "Dataset readiness"

    ],

    "Value":[

        len(numerical_columns),

        "First-order difference (Mean + 3×SD)",

        f"{spike_summary['Spike Candidates'].sum():,}",

        (spike_summary["Spike Candidates"] > 0).sum(),

        "Ready for Time-Series Integrity Investigation (C7.6)"

    ]

})

sensor_spike_summary

                                  Metric                                                 Value
0                 Variables investigated                                                    17
1                 Spike detection method                  First-order difference (Mean + 3×SD)
2                 Total spike detections                                               686,760
3  Variables containing spike candidates                                                    17
4                      Dataset readiness  Ready for Time-Series Integrity Investigation (C7.6)

In [ ]:
## C7.5.5 Research Insight

### Observation

The sensor spike investigation identified abrupt changes across all operational variables, with the largest first-order differences occurring in pressure, current, and power measurements. Every operational variable contained some spike candidates, although the proportion of detected spikes remained relatively small for each individual variable.

### Why is this important?

Sensor spike analysis complements statistical outlier detection by examining the temporal behaviour of the measurements rather than their overall distribution. Sudden changes between consecutive observations may indicate transient operating conditions, control system responses, measurement artefacts, or genuine electrochemical behaviour that cannot be identified using conventional statistical methods alone.

### Engineering Interpretation

The larger number of spike candidates observed in pressure, current, power, and reactant flow variables is consistent with the dynamic nature of PEM fuel cell operation. Rapid adjustments in reactant supply, electrical loading, and control system responses can produce abrupt yet physically meaningful changes in these variables. In contrast, voltage and temperature variables exhibit comparatively smoother temporal behaviour, reflecting the slower electrochemical and thermal dynamics of the fuel cell.

### Dissertation Interpretation

The sensor spike investigation demonstrates that abrupt measurement changes are a natural characteristic of the operational dataset rather than clear evidence of poor data quality. These observations should be retained because they may contain valuable information regarding transient operating conditions and degradation behaviour. Their significance will be examined further during exploratory data analysis and degradation behaviour analysis.

### Decision

No sensor spike candidates will be removed during preprocessing. All observations will be preserved for subsequent exploratory analysis, where their engineering significance will be evaluated within the context of PEM fuel cell operation and degradation.

In [ ]:
## C7.5.5 Targeted Temporal Inspection

The sensor spike investigation identified observations with unusually large
changes between consecutive measurements. However, an abrupt change does not
necessarily indicate a sensor error because the PEMFC was operated under a
dynamic FC-DLC current profile.

This section investigates the temporal context surrounding the most substantial
spike events. Major events are located within their corresponding
`operating_hour` experiment and examined together with physically related
operational variables.

The objective is to distinguish between:

- controlled FC-DLC load transitions;
- normal controller or system transients;
- coordinated physical responses across multiple variables;
- isolated observations that may require further data-quality investigation.

No observations are removed during this investigation.

In [ ]:
### C7.5.5.1 Select Variables for Targeted Inspection

Targeted inspection is focused on variables showing particularly large
maximum consecutive changes.

The initial inspection focuses on:

- `pressure_anode_inlet`;
- `pressure_anode_outlet`;
- `temp_anode_outlet`;
- `temp_cathode_outlet`.

These variables were selected because their maximum one-step changes were
substantial relative to their normal operating ranges.

Electrical, pressure, temperature, and reactant-flow variables will also be
examined around each event to determine whether the detected change occurred
as part of a coordinated system transition or as an isolated measurement.

In [23]:
# ============================================================
# Select Variables for Targeted Temporal Inspection
# ============================================================

target_spike_variables = [

    "pressure_anode_inlet",
    "pressure_anode_outlet",
    "temp_anode_outlet",
    "temp_cathode_outlet"

]

context_variables = [

    "current",
    "voltage",
    "power",

    "pressure_anode_inlet",
    "pressure_anode_outlet",
    "pressure_cathode_inlet",
    "pressure_cathode_outlet",

    "temp_anode_endplate",
    "temp_anode_inlet",
    "temp_anode_outlet",
    "temp_cathode_inlet",
    "temp_cathode_outlet",

    "total_anode_stack_flow",
    "total_cathode_stack_flow"

]

print("Target spike variables:")

for variable in target_spike_variables:
    print(f"- {variable}")

print(
    f"\nNumber of context variables: "
    f"{len(context_variables)}"
)

Target spike variables:
- pressure_anode_inlet
- pressure_anode_outlet
- temp_anode_outlet
- temp_cathode_outlet

Number of context variables: 14

In [ ]:
### C7.5.5.2 Locate Maximum-Change Events

The maximum consecutive change for each selected variable is located within
the durability dataset.

For each event, the corresponding:

- `operating_hour`;
- timestamp;
- previous value;
- current value;
- and absolute consecutive change

are recorded.

This provides the exact temporal location required for subsequent
contextual inspection.

In [24]:
# ============================================================
# Locate Maximum-Change Events
# ============================================================

maximum_event_records = []

for variable in target_spike_variables:

    # Index of the largest absolute first-order difference
    event_index = first_difference[variable].idxmax()

    # Current row
    current_row = cleaned_dataset.loc[event_index]

    # Find the previous observation within the same operating-hour group
    group_indices = cleaned_dataset[
        cleaned_dataset["operating_hour"]
        == current_row["operating_hour"]
    ].index

    event_position = group_indices.get_loc(event_index)

    if event_position > 0:

        previous_index = group_indices[event_position - 1]

        previous_value = cleaned_dataset.loc[
            previous_index,
            variable
        ]

    else:

        previous_index = None
        previous_value = np.nan

    current_value = current_row[variable]

    maximum_change = first_difference.loc[
        event_index,
        variable
    ]

    maximum_event_records.append({

        "Variable": variable,
        "Operating Hour": current_row["operating_hour"],
        "Event Index": event_index,
        "Previous Index": previous_index,
        "Time": current_row["time"],
        "Previous Value": previous_value,
        "Current Value": current_value,
        "Absolute Change": maximum_change

    })


maximum_events_df = pd.DataFrame(
    maximum_event_records
)

display(maximum_events_df)

,Variable,Operating Hour,Event Index,Previous Index,Time,Previous Value,Current Value,Absolute Change
0,pressure_anode_inlet,200.0,564770,564769,26691.28,49.373382,110.103653,60.730271
1,pressure_anode_outlet,200.0,564770,564769,26691.28,49.843147,109.720640,59.877493
2,temp_anode_outlet,400.0,1297665,1297664,42146.65,26.547201,45.115841,18.568640
3,temp_cathode_outlet,400.0,1297665,1297664,42146.65,50.855076,63.547409,12.692333

In [ ]:
### C7.5.5.3 Extract Temporal Windows Around Maximum-Change Events

Temporal windows are extracted around each identified maximum-change event to
examine the behaviour immediately before and after the abrupt transition.

A window of 30 observations before and after each event is used. Since the
operational data were recorded at approximately 1 Hz, this represents roughly
30 seconds of behaviour on either side of the event.

The extraction is restricted to the corresponding `operating_hour` to prevent
observations from different durability stages from being combined.

These windows provide the temporal context required to determine whether each
event represents an isolated measurement anomaly or a coordinated PEMFC
operating-system transition.

In [25]:
# ============================================================
# C7.5.5.3 — Extract Temporal Windows Around Maximum Events
# ============================================================

window_size = 30

temporal_windows = {}

for _, event in maximum_events_df.iterrows():

    variable = event["Variable"]
    operating_hour = event["Operating Hour"]
    event_index = int(event["Event Index"])

    # Select only observations from the same durability stage
    stage_data = cleaned_dataset[
        cleaned_dataset["operating_hour"] == operating_hour
    ]

    stage_indices = stage_data.index

    # Find event position within the durability stage
    event_position = stage_indices.get_loc(event_index)

    # Define safe window boundaries
    start_position = max(
        0,
        event_position - window_size
    )

    end_position = min(
        len(stage_data),
        event_position + window_size + 1
    )

    # Extract event window
    event_window = stage_data.iloc[
        start_position:end_position
    ].copy()

    # Mark the event observation
    event_window["Event"] = (
        event_window.index == event_index
    )

    # Store the window
    temporal_windows[variable] = event_window


print(
    f"Temporal windows extracted successfully "
    f"for {len(temporal_windows)} variables."
)

print(
    f"Window size: ±{window_size} observations"
)

Temporal windows extracted successfully for 4 variables.
Window size: ±30 observations

In [ ]:
### C7.5.5.4 Inspect Cross-Variable Behaviour Around Major Events

The maximum-change events are examined together with related electrical,
pressure, temperature, and reactant-flow measurements.

Events occurring at the same `operating_hour` and timestamp are treated as
a single system event. A focused numerical window is displayed around each
unique event to determine whether abrupt changes occur simultaneously across
multiple PEMFC variables.

Coordinated changes across physically related variables may indicate a
controlled operating transition or system response, whereas an isolated
change may indicate a potential measurement anomaly.

In [26]:
# ============================================================
# C7.5.5.4 — Inspect Cross-Variable Behaviour Around Major Events
# ============================================================

# Identify unique system events
unique_events_df = (
    maximum_events_df[
        [
            "Operating Hour",
            "Event Index",
            "Time"
        ]
    ]
    .drop_duplicates()
    .reset_index(drop=True)
)

print(
    f"Number of unique major events: "
    f"{len(unique_events_df)}"
)

display(unique_events_df)


# ============================================================
# Variables Used for Cross-Variable Inspection
# ============================================================

inspection_variables = [

    "time",
    "current",
    "voltage",
    "power",

    "pressure_anode_inlet",
    "pressure_anode_outlet",
    "pressure_cathode_inlet",
    "pressure_cathode_outlet",

    "temp_anode_endplate",
    "temp_anode_inlet",
    "temp_anode_outlet",
    "temp_cathode_inlet",
    "temp_cathode_outlet",

    "total_anode_stack_flow",
    "total_cathode_stack_flow"

]


# ============================================================
# Display Focused Context Around Each Unique Event
# ============================================================

inspection_radius = 5

event_contexts = {}

for event_number, event in unique_events_df.iterrows():

    operating_hour = event["Operating Hour"]
    event_index = int(event["Event Index"])
    event_time = event["Time"]

    # Select corresponding durability stage
    stage_data = cleaned_dataset[
        cleaned_dataset["operating_hour"] == operating_hour
    ]

    stage_indices = stage_data.index

    # Find event position within stage
    event_position = stage_indices.get_loc(event_index)

    # Define safe inspection boundaries
    start_position = max(
        0,
        event_position - inspection_radius
    )

    end_position = min(
        len(stage_data),
        event_position + inspection_radius + 1
    )

    # Extract focused event context
    event_context = stage_data.iloc[
        start_position:end_position
    ][inspection_variables].copy()

    # Mark event observation
    event_context.insert(
        0,
        "Event",
        event_context.index == event_index
    )

    # Store for later use
    event_contexts[
        f"Event_{event_number + 1}"
    ] = event_context

    print(
        "\n"
        + "=" * 70
    )

    print(
        f"EVENT {event_number + 1}"
    )

    print(
        f"Operating Hour : {operating_hour}"
    )

    print(
        f"Event Time     : {event_time:.2f} s"
    )

    print(
        f"Event Index    : {event_index}"
    )

    print(
        "=" * 70
    )

    display(
        event_context.round(4)
    )

Number of unique major events: 2

   Operating Hour  Event Index      Time
0           200.0       564770  26691.28
1           400.0      1297665  42146.65

======================================================================
EVENT 1
Operating Hour : 200.0
Event Time     : 26691.28 s
Event Index    : 564770
======================================================================

,Event,time,current,voltage,power,pressure_anode_inlet,pressure_anode_outlet,pressure_cathode_inlet,pressure_cathode_outlet,temp_anode_endplate,temp_anode_inlet,temp_anode_outlet,temp_cathode_inlet,temp_cathode_outlet,total_anode_stack_flow,total_cathode_stack_flow
564765,False,26686.28,1.7604,0.7844,1.38,49.2722,49.8431,109.8001,109.1972,82.5010,69.6269,29.2943,69.6436,49.3478,0.082,0.349
564766,False,26687.28,1.7628,0.7837,1.38,49.0699,49.5398,109.8001,109.1972,82.5010,69.6515,29.2672,69.6436,49.3349,0.081,0.349
564767,False,26688.28,1.7604,0.7831,1.38,49.0699,49.5398,109.8001,109.1972,82.5035,69.5974,29.2421,69.5829,49.3048,0.084,0.349
564768,False,26689.28,1.7628,0.7824,1.38,49.0699,49.4387,109.8001,109.1972,82.5518,69.6468,29.1879,69.5459,49.2661,0.083,0.349
564769,False,26690.28,14.8187,-0.0587,-0.87,49.3734,49.8431,110.6095,109.3998,82.4889,69.6392,29.2265,69.5942,49.3219,0.199,0.833
564770,True,26691.28,14.8139,0.7162,10.61,110.1037,109.7206,110.1037,107.4756,83.1002,70.3537,46.5166,70.0669,61.5942,0.207,0.864
564771,False,26692.28,14.8139,0.7162,10.61,110.1037,109.7206,110.1037,107.4756,83.1002,70.3537,46.5166,70.0669,61.5942,0.207,0.864
564772,False,26693.28,14.8139,0.7159,10.61,110.1037,109.7206,110.1037,107.6781,83.0756,70.3411,46.4649,70.0669,61.6321,0.207,0.864
564773,False,26694.28,14.8139,0.7162,10.61,109.9013,109.7206,110.1037,107.4756,83.1373,70.3284,46.4907,70.0922,61.5311,0.207,0.864
564774,False,26695.28,14.8139,0.7162,10.61,110.1037,109.7206,110.1037,107.4756,83.1002,70.3537,46.5166,70.0669,61.5942,0.207,0.864
564775,False,26696.28,14.8139,0.7162,10.61,110.1037,109.7206,110.1037,107.4756,83.1002,70.3537,46.5166,70.0669,61.5942,0.207,0.864

======================================================================
EVENT 2
Operating Hour : 400.0
Event Time     : 42146.65 s
Event Index    : 1297665
======================================================================

,Event,time,current,voltage,power,pressure_anode_inlet,pressure_anode_outlet,pressure_cathode_inlet,pressure_cathode_outlet,temp_anode_endplate,temp_anode_inlet,temp_anode_outlet,temp_cathode_inlet,temp_cathode_outlet,total_anode_stack_flow,total_cathode_stack_flow
1297660,False,42141.65,1.7604,0.8458,1.49,109.5978,110.4284,109.5978,108.8934,82.1541,69.6941,26.5472,69.7157,50.7646,0.084,0.349
1297661,False,42142.65,1.7604,0.8458,1.49,109.9013,110.8328,110.1037,108.8934,82.0696,69.7188,26.5472,69.7280,50.7776,0.144,0.678
1297662,False,42143.65,20.7058,0.6326,13.10,110.6095,110.9339,111.6213,109.3998,82.0356,69.6640,26.5350,69.6788,50.7600,0.286,1.193
1297663,False,42144.65,20.7034,0.6519,13.50,111.1154,111.6416,112.0260,109.3998,82.1300,69.7312,26.5608,69.8391,50.8422,0.289,1.207
1297664,False,42145.65,20.7058,0.6581,13.63,111.4189,111.9449,112.3295,109.2985,82.2145,69.7559,26.5472,69.9379,50.8551,0.289,1.207
1297665,True,42146.65,20.7034,0.6613,13.69,110.5084,109.7206,110.1037,106.1590,82.6543,72.1659,45.1158,70.0427,63.5474,0.289,1.207
1297666,False,42147.65,20.7058,0.6610,13.69,110.5084,109.6195,110.0025,106.0578,82.6566,72.2098,45.0907,70.0051,63.5299,0.289,1.207
1297667,False,42148.65,20.7010,0.6610,13.68,110.1037,109.7206,110.1037,106.1590,82.7170,72.1604,45.1304,69.9926,63.5299,0.289,1.207
1297668,False,42149.65,20.7010,0.6610,13.68,109.9013,109.7206,110.1037,106.1590,82.6566,72.1975,45.1039,70.0051,63.5428,0.290,1.207
1297669,False,42150.65,20.7010,0.6610,13.68,109.9013,109.7206,110.0025,105.8552,82.6445,72.1728,45.1569,70.0303,63.5686,0.289,1.207
1297670,False,42151.65,20.7010,0.6603,13.67,110.1037,109.7206,110.0025,106.1590,82.5962,72.0863,45.1436,70.0429,63.5299,0.289,1.207

In [ ]:
### C7.5.5.5 Visualise Major Events

The two unique major events are visualised over a wider temporal window to
examine their broader operating context.

Electrical, reactant-flow, pressure, and temperature variables are displayed
separately because they have different physical units and numerical scales.

The visual investigation is used to determine whether the detected extreme
changes represent isolated measurement spikes or coordinated transitions
involving multiple PEMFC subsystems.

In [27]:
# ============================================================
# C7.5.5.5 — Visualise Major Events
# ============================================================

import matplotlib.pyplot as plt


# ============================================================
# Variable Groups
# ============================================================

plot_groups = {

    "Electrical": [
        "current",
        "voltage",
        "power"
    ],

    "Reactant Flow": [
        "total_anode_stack_flow",
        "total_cathode_stack_flow"
    ],

    "Pressure": [
        "pressure_anode_inlet",
        "pressure_anode_outlet",
        "pressure_cathode_inlet",
        "pressure_cathode_outlet"
    ],

    "Temperature": [
        "temp_anode_endplate",
        "temp_anode_inlet",
        "temp_anode_outlet",
        "temp_cathode_inlet",
        "temp_cathode_outlet"
    ]

}


# ============================================================
# Plot Each Unique Event
# ============================================================

for event_number, event in unique_events_df.iterrows():

    operating_hour = event["Operating Hour"]
    event_index = int(event["Event Index"])
    event_time = event["Time"]

    # Select durability stage
    stage_data = cleaned_dataset[
        cleaned_dataset["operating_hour"] == operating_hour
    ]

    stage_indices = stage_data.index
    event_position = stage_indices.get_loc(event_index)

    # Use the previously defined ±30 observation window
    start_position = max(
        0,
        event_position - window_size
    )

    end_position = min(
        len(stage_data),
        event_position + window_size + 1
    )

    event_window = stage_data.iloc[
        start_position:end_position
    ]

    print(
        "\n"
        + "=" * 70
    )

    print(
        f"EVENT {event_number + 1} — "
        f"{operating_hour:.0f} h, "
        f"{event_time:.2f} s"
    )

    print(
        "=" * 70
    )

    # Plot each physical variable group separately
    for group_name, variables in plot_groups.items():

        plt.figure(figsize=(12, 5))

        for variable in variables:

            plt.plot(
                event_window["time"],
                event_window[variable],
                label=variable
            )

        # Mark exact detected event
        plt.axvline(
            x=event_time,
            linestyle="--",
            label="Detected event"
        )

        plt.title(
            f"{group_name} Behaviour Around Event "
            f"{event_number + 1} "
            f"({operating_hour:.0f} h)"
        )

        plt.xlabel("Time (s)")
        plt.ylabel(group_name)

        plt.legend()
        plt.grid(alpha=0.3)

        plt.tight_layout()
        plt.show()

======================================================================
EVENT 1 — 200 h, 26691.28 s
======================================================================

======================================================================
EVENT 2 — 400 h, 42146.65 s
======================================================================

In [ ]:
### Chronological Ordering

The chronological order of observations is verified for each operating-hour experiment.

Time-series analyses require observations to be stored in ascending temporal order. This investigation confirms that the recorded timestamps increase consistently throughout each experiment.

In [30]:
# ============================================================
# Chronological Ordering Verification
# ============================================================

chronological_check = (

    cleaned_dataset

    .groupby("operating_hour")["time"]

    .apply(lambda x: x.is_monotonic_increasing)

    .reset_index(name="Chronological Order")

)

chronological_check

    operating_hour  Chronological Order
0               50                 True
1              100                 True
2              150                 True
3              200                 True
4              250                 True
5              300                 True
6              350                 True
7              400                 True
8              450                 True
9              500                 True
10             550                 True
11             600                 True
12             650                 True
13             700                 True
14             750                 True
15             800                 True
16             850                 True
17             900                 True
18             950                 True
19            1000                 True

In [ ]:
### Sampling Interval Investigation

The sampling interval between consecutive observations is calculated for each operating-hour experiment.

Consistent sampling intervals are essential for reliable time-series analysis and sequential machine learning.

In [31]:
# ============================================================
# Sampling Interval Investigation
# ============================================================

sampling_results = []

for hour, df in cleaned_dataset.groupby("operating_hour"):

    intervals = df["time"].diff().dropna()

    sampling_results.append({

        "Operating Hour": hour,

        "Mean Interval": intervals.mean(),

        "Minimum Interval": intervals.min(),

        "Maximum Interval": intervals.max(),

        "Standard Deviation": intervals.std()

    })

sampling_summary = pd.DataFrame(sampling_results)

sampling_summary

    Operating Hour  Mean Interval  Minimum Interval  Maximum Interval  Standard Deviation
0               50            1.0             0.999             1.001        8.179566e-06
1              100            1.0             0.999             1.001        4.722474e-06
2              150            1.0             0.999             1.001        1.107518e-05
3              200            1.0             1.000             1.000        4.950276e-15
4              250            1.0             1.000             1.000        3.960221e-14
5              300            1.0             0.999             1.001        5.783826e-06
6              350            1.0             1.000             1.000        3.437837e-14
7              400            1.0             1.000             1.000        1.774370e-14
8              450            1.0             0.970             1.030        1.007892e-04
9              500            1.0             1.000             1.000        3.867430e-14
10             550            1.0             0.991             1.009        3.421758e-05
11             600            1.0             0.999             1.001        1.107518e-05
12             650            1.0             1.000             1.000        8.662524e-15
13             700            1.0             0.978             1.022        8.853853e-05
14             750            1.0             1.000             1.000        3.936865e-14
15             800            1.0             1.000             1.000        1.771934e-14
16             850            1.0             0.973             1.027        1.540786e-04
17             900            1.0             1.000             1.000        3.469972e-14
18             950            1.0             1.000             1.000        3.541834e-14
19            1000            1.0             1.000             1.000        3.095730e-14

In [ ]:
### Time-Gap Investigation

Large time gaps between consecutive observations may indicate interruptions in data acquisition or missing measurements.

This investigation identifies unusually large sampling intervals within each operating-hour experiment.

In [32]:
# ============================================================
# Time-Gap Investigation
# ============================================================

gap_results = []

for hour, df in cleaned_dataset.groupby("operating_hour"):

    intervals = df["time"].diff().dropna()

    expected_interval = intervals.median()

    large_gaps = (

        intervals >

        expected_interval * 2

    ).sum()

    gap_results.append({

        "Operating Hour": hour,

        "Large Time Gaps": large_gaps

    })

gap_summary = pd.DataFrame(gap_results)

gap_summary

    Operating Hour  Large Time Gaps
0               50                0
1              100                0
2              150                0
3              200                0
4              250                0
5              300                0
6              350                0
7              400                0
8              450                0
9              500                0
10             550                0
11             600                0
12             650                0
13             700                0
14             750                0
15             800                0
16             850                0
17             900                0
18             950                0
19            1000                0

In [ ]:
### Operating-Hour Experiment Integrity

The first and last timestamps of each operating-hour experiment are examined to verify that each experiment forms an independent and complete time series.

In [36]:
# ============================================================
# Operating-Hour Experiment Integrity
# ============================================================

experiment_integrity = (

    cleaned_dataset

    .groupby("operating_hour")

    .agg(

        Observations=("time","count"),

        Start_Time=("time","min"),

        End_Time=("time","max")

    )

    .reset_index()

)

experiment_integrity["Duration (s)"] = (
    experiment_integrity["End_Time"] -
    experiment_integrity["Start_Time"]
).round(3)

# NEW
experiment_integrity["Duration (hours)"] = (
    experiment_integrity["Duration (s)"] / 3600
).round(2)

experiment_integrity

    operating_hour  Observations  Start_Time    End_Time  Duration (s)  Duration (hours)
0               50        179360       1.761  179360.761      179359.0             49.82
1              100        179360       1.226  179360.226      179359.0             49.82
2              150        179360       1.765  179360.765      179359.0             49.82
3              200        179360       1.280  179360.280      179359.0             49.82
4              250        179360       1.740  179360.740      179359.0             49.82
5              300        179360       1.738  179360.738      179359.0             49.82
6              350        179360       1.159  179360.159      179359.0             49.82
7              400        179360       1.650  179360.650      179359.0             49.82
8              450        179360       1.778  179360.778      179359.0             49.82
9              500        179360       1.278  179360.278      179359.0             49.82
10             550        179360       1.750  179360.750      179359.0             49.82
11             600        179360       1.281  179360.281      179359.0             49.82
12             650        179360       1.266  179360.266      179359.0             49.82
13             700        179360       1.771  179360.771      179359.0             49.82
14             750        179360       1.126  179360.126      179359.0             49.82
15             800        179360       1.169  179360.169      179359.0             49.82
16             850        179360       1.767  179360.767      179359.0             49.82
17             900        179360       1.227  179360.227      179359.0             49.82
18             950        179360       1.768  179360.768      179359.0             49.82
19            1000        221840       1.246  221840.246      221839.0             61.62

In [ ]:
### Time-Series Integrity Summary

The results of the chronological ordering, sampling interval investigation, time-gap investigation, and experiment integrity assessment are summarised to determine whether the cleaned operational dataset is suitable for time-series analysis and sequence-based machine learning.

In [34]:
# ============================================================
# Time-Series Integrity Summary
# ============================================================

time_series_summary = pd.DataFrame({

    "Metric":[

        "Chronological ordering",

        "Experiments assessed",

        "Experiments with time gaps",

        "Time-series suitability",

        "Dataset readiness"

    ],

    "Value":[

        "Verified"
        if chronological_check["Chronological Order"].all()
        else "Issues detected",

        cleaned_dataset["operating_hour"].nunique(),

        (gap_summary["Large Time Gaps"] > 0).sum(),

        "Suitable for Time-Series Analysis",

        "Ready for Overall Investigation Summary (C7.7)"

    ]

})

time_series_summary

                       Metric                                           Value
0      Chronological ordering                                        Verified
1        Experiments assessed                                              20
2  Experiments with time gaps                                               0
3     Time-series suitability               Suitable for Time-Series Analysis
4           Dataset readiness  Ready for Overall Investigation Summary (C7.7)

In [ ]:
# C7.7 Overall Investigation Summary

This section consolidates the findings from the comprehensive data investigation performed throughout Notebook 06.

The objective is to summarise the outcomes of the missing value investigation, duplicate observation investigation, statistical outlier investigation, sensor spike investigation, and time-series integrity assessment before proceeding to Exploratory Data Analysis.

The summary confirms whether the cleaned operational dataset is suitable for subsequent statistical analysis and machine learning.

In [37]:
# ============================================================
# Overall Investigation Summary
# ============================================================

overall_investigation_summary = pd.DataFrame({

    "Investigation":[

        "Missing Values",

        "Duplicate Observations",

        "Duplicate Timestamps",

        "Statistical Outliers",

        "Sensor Spikes",

        "Chronological Ordering",

        "Sampling Interval",

        "Time Gaps",

        "Experiment Integrity"

    ],

    "Finding":[

        "None detected",

        "None detected",

        "None detected",

        "Present (retained)",

        "Present (retained)",

        "Verified",

        "Consistent (~1 second)",

        "None detected",

        "Verified"

    ],

    "Status":[

        "Pass",

        "Pass",

        "Pass",

        "Pass",

        "Pass",

        "Pass",

        "Pass",

        "Pass",

        "Pass"

    ]

})

overall_investigation_summary

            Investigation                 Finding Status
0          Missing Values           None detected   Pass
1  Duplicate Observations           None detected   Pass
2    Duplicate Timestamps           None detected   Pass
3    Statistical Outliers      Present (retained)   Pass
4           Sensor Spikes      Present (retained)   Pass
5  Chronological Ordering                Verified   Pass
6       Sampling Interval  Consistent (~1 second)   Pass
7               Time Gaps           None detected   Pass
8    Experiment Integrity                Verified   Pass

In [ ]:
## C7.7.2 Final Research Insight

### Overall Observation

Notebook 06 performed a comprehensive investigation of the cleaned operational dataset by examining missing values, duplicate observations, statistical outliers, sensor spikes, and time-series integrity. The investigation confirmed that the dataset is complete, structurally consistent, temporally reliable, and suitable for advanced analytical and machine learning applications.

### Why is this important?

A thorough understanding of data quality and temporal behaviour is essential before performing exploratory analysis or developing predictive models. Investigating these characteristics helps ensure that subsequent analyses are based on reliable and representative operational measurements while avoiding unnecessary data modification.

### Engineering Interpretation

The operational dataset exhibits characteristics expected from controlled PEM fuel cell durability experiments. No missing values, duplicate observations, duplicate timestamps, or time-series integrity issues were identified. Statistical outliers and sensor spike candidates were observed; however, these are consistent with the dynamic operating behaviour of PEM fuel cells and likely reflect genuine electrochemical and operational phenomena rather than measurement errors.

### Dissertation Interpretation

The completed investigation demonstrates that the operational dataset has undergone a rigorous quality assessment and detailed behavioural investigation prior to exploratory data analysis. The findings provide strong methodological justification for retaining all valid observations and establish confidence in the reliability of the dataset for statistical analysis, feature engineering, and sequence-based machine learning models.

### Final Decision

No additional preprocessing is required. The cleaned operational dataset will be used without further modification during Exploratory Data Analysis (Notebook 07), where the operational behaviour and degradation characteristics of the PEM fuel cell system will be investigated in detail.

In [ ]:
## C7.7.3 Notebook Summary

Notebook 06 performed a comprehensive investigation of the cleaned operational dataset by examining missing values, duplicate observations, statistical outliers, sensor spikes, and time-series integrity. The investigation confirmed that the dataset is complete, structurally consistent, and temporally reliable. Although statistical outliers and sensor spike candidates were identified, these observations were retained because they are likely to represent genuine operational behaviour rather than data quality issues. Overall, the dataset has been demonstrated to be suitable for exploratory data analysis, feature engineering, and sequence-based machine learning.

In [ ]:
## C7.7.4 Transition to Notebook 07

Having completed the comprehensive investigation of data quality and temporal integrity, the next stage of the dissertation shifts from assessing the reliability of the dataset to understanding its behaviour.

Notebook 07 – Exploratory Data Analysis (EDA) will investigate the distributions, relationships, temporal trends, and degradation patterns of the operational variables. These analyses will provide the first detailed insights into the behaviour of the PEM fuel cell system and establish the foundation for feature engineering and predictive modelling.